src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <formula>Subscription__r.Product_Name__r.Name</formula>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CreationStage__c</fullName>
        <label>CreationStage</label>
        <picklist>
            <picklistValues>
                <fullName>MQL</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SAL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>MQL</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SRL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SQL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SDL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Plan__c</fullName>
        <label>Plan</label>
        <picklist>
            <controllingField>Product__c</controllingField>
            <picklistValues>
                <fullName>Fusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Growth</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scale</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>Kayako 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Kayako 4 OnDemand)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Kayako 3 -&gt; 4 OnDemand)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Kayako 4 (July 2014))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (July 2016)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Download Perpetual Upgrade (July 2016))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Nov 2016)</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Download Perpetual Upgrade (Nov 2016))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 4 (Download Perpetual to Subscription (Dec 2016))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 4 Renewals (Nov 2010)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 4 Renewals (April 2013)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 4 OnDemand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 4 (July 2014)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 3 -&gt; 4 Renewals (Nov 2010)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 3 -&gt; 4 OnDemand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Kayako 4 (Download Perpetual to Subscription (Dec 2016)))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (June 2017)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Download Perpetual Upgrade (June 2017))</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SlackTest.cls
@IsTest
public class SlackTest
{
	public static TestMethod void PayloadAsJsonString()
    {
        String payload = Slack.PayloadAsString('this is the text content');
        
        Map <String, Object> decoded = (Map <String, Object>) JSON.deserializeUntyped(payload);
        
        System.assert(decoded.containsKey('icon_emoji'));
        System.assert(decoded.containsKey('username'));
        System.assert(decoded.containsKey('text'));
        System.assertEquals('this is the text content', decoded.get('text'));
    }
    
    @IsTest(SeeAllData = true)
    public static void LeadAsAttachmentPayload()
    {
        List<Lead> lead = [SELECT id, email, name, phone, stage__c, status, CreationStage__c, 
                     leadSource, country, ownerid, createdDate 
                     FROM lead limit 2];
        
        Map <String, Object> payload = Slack.BuildPayload('this is the text', 'this is some text content', lead);
        
        System.assert(payload.containsKey('attachments'));
        System.assert(payload.containsKey('username'));
        System.assert(payload.containsKey('icon_emoji'));
    }
    
    @IsTest(SeeAllData = true)
    public static void OpportunityAsAttachmentPayload()
    {
        List<Opportunity> o = [select name, stagename, ownerid, amount, product__c, type, plan__c, leadsource from opportunity limit 2];
        
        Map <String, Object> payload = Slack.BuildPayload('this is the text', 'this is some text content', o);
        
        System.assert(payload.containsKey('attachments'));
        System.assert(payload.containsKey('username'));
        System.assert(payload.containsKey('icon_emoji'));
    }
    
    @IsTest(SeeAllData = true)
    public static void AccountAsAttachmentPayload()
    {
        List <Account> a = [select ownerId, name, phone, website from account limit 2];
        
        Map <String, Object> payload = Slack.BuildPayload('this is the text', 'this is some text content', a);
        
        System.assert(payload.containsKey('attachments'));
        System.assert(payload.containsKey('username'));
        System.assert(payload.containsKey('icon_emoji'));
    }
    
    @IsTest(SeeAllData = true)
    public static void ContactAsAttachmentPayload()
    {
        List <Contact> c = [select ownerId, name, phone, email from contact limit 2];
        
        Map <String, Object> payload = Slack.BuildPayload('this is the text', 'this is some text content', c);
        
        System.assert(payload.containsKey('attachments'));
        System.assert(payload.containsKey('username'));
        System.assert(payload.containsKey('icon_emoji'));
    }
}