src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <formula>Subscription__r.Instance_Expiry_Date__c</formula>
        <label>Expiry Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SecurityToken__c</fullName>
        <label>Security Token</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DirOutput/objects/Instance__c.object
<CustomObject>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>InstanceId__c</fullName>
        <formula>TEXT(Instance_ID__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Instance ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Instance_ID__c</fullName>
        <label>Instance ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Instance</label>
    <nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Instance_ID__c</fullName>
        <formula>Instance__r.Instance_ID__c</formula>
        <label>Instance ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Instance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Instance</label>
        <referenceTo>Instance__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DirOutput/classes/ValidateVATValidationTest.cls
@isTest
public class ValidateVATValidationTest {
    public static testMethod void validateVATTest1(){
        
        account acc = new account();
        acc.name = 'test';
        insert acc;
        
        Instance__c i = new Instance__c();
        i.Name='test.kayako.com';
        i.Expiry_Date__c = date.today();
        i.Instance_ID__c = 1234567;
        i.UUID__c = 'uuid1236513789567238';
        insert i; 
        
        
        opportunity o = new opportunity();
        o.name = 'test';
        o.AccountId = acc.id;
        o.CloseDate =date.today()+30;
        o.StageName = 'Review & Negotiation';
        o.Instance__c = i.Id;
        
        insert o;
        
        
        zqu__quote__c q = new zqu__quote__c();
        q.zqu__VAT_ID__c = 'NL121345';
        q.Name = 'test';
        q.zqu__Opportunity__c = o.id; 
        q.SecurityToken__c = '67123895fgahjsfk';
        q.InstanceID__c = 37893;
        
        insert q;
        
        Test.setCurrentPage(Page.validatevat);
        ValidateVATValidation vatvalidation = new ValidateVATValidation(new ApexPages.StandardController(q));
       
        vatvalidation.validate();
        
		

        
        
    }
    
    public static testMethod void validateVATTest2(){
        
        account acc = new account();
        acc.name = 'test';
        insert acc;
        
        Instance__c i = new Instance__c();
        i.Name='test.kayako.com';
        i.Expiry_Date__c = date.today();
        i.Instance_ID__c = 1234567;
        i.UUID__c = 'uuid1236513789567238';
        insert i; 
        
        
        opportunity o = new opportunity();
        o.name = 'test';
        o.AccountId = acc.id;
        o.CloseDate =date.today()+30;
        o.StageName = 'Review & Negotiation';
        o.Instance__c = i.Id;
        
        insert o;
        
        
        zqu__quote__c q = new zqu__quote__c();
        q.zqu__VAT_ID__c = '';
        q.Name = 'test';
        q.zqu__Opportunity__c = o.id; 
        q.SecurityToken__c = '67123895fgahjsfk';
        q.InstanceID__c = 37893;
        
        insert q;
        
        Test.setCurrentPage(Page.validatevat);
        ValidateVATValidation vatvalidation = new ValidateVATValidation(new ApexPages.StandardController(q));
        vatvalidation.validate();
        
		

        
        
    }
    
    
   
}