src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <formula>Subscription__r.Instance_Expiry_Date__c</formula>
        <label>Expiry Date</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DirOutput/objects/Instance__c.object
<CustomObject>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>InstanceId__c</fullName>
        <formula>TEXT(Instance_ID__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Instance ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Instance_ID__c</fullName>
        <label>Instance ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Instance</label>
    <nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DirOutput/objects/KayakoAuditorKey__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>KayakoAuditorKey</label>
</CustomObject>

src/objects/KayakoMetricsKey__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Kayako Metrics Key is used to communicate with backend to get the Metrics related to an Instance.</description>
    <fields>
        <fullName>Key__c</fullName>
        <description>This is secret key which is used to communicate with backend in order to get the metrics.</description>
        <label>Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>KayakoMetricsKey</label>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Instance_ID__c</fullName>
        <formula>Instance__r.Instance_ID__c</formula>
        <label>Instance ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Instance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Instance</label>
        <referenceTo>Instance__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KA_Product__c</fullName>
        <label>Product</label>
        <picklist>
            <picklistValues>
                <fullName>Fusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Growth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scale</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Instance_ID__c</fullName>
        <formula>Instance__r.Instance_ID__c</formula>
        <label>Instance ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Instance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Instance</label>
        <referenceTo>Instance__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DirOutput/classes/TestBatchInstanceExpiryUpdater.cls
@isTest
public class TestBatchInstanceExpiryUpdater {
    static testmethod void test() {
        
      
       KayakoMetricsKey__c kmk = new KayakoMetricsKey__c();
       kmk.name = 'test';
       kmk.key__c = 'testing';
       insert kmk;
       
       KayakoAuditorKey__c km = new KayakoAuditorKey__c();
       km.name = 'tester';
       km.key__c = 'testing123';
       insert km;
       
       List<Instance__c> aList = new List<Instance__c>();
       
            Instance__c a = new Instance__c();
            a.name='test.instance.com';
            a.uuid__c ='fhjk373374fhfjdkshfjks';
            a.Expiry_Date__c = DateTime.Now();
            a.instance_id__c = 444;
            insert a;
        
             
           Lead l = new Lead();
           l.lastName = 'test';
           l.Email = 'test@test.com';
           l.Company = 'test company';
           l.Instance__c = a.id;
           l.ka_product__c = 'Standard';
           insert l;
           
        
           Account acc = new Account();
           acc.name = 'test';
           insert acc ;
        
           Opportunity o = new Opportunity();
           o.Name = 'test';
           o.accountId =  acc.id;
           o.StageName = 'Value Proposition';
           o.CloseDate = Date.today()+30;
           o.Instance__c = a.id;
           o.type = 'New Business';
           insert o;
        
            Zuora__Subscription__c zs= new Zuora__Subscription__c();
            zs.Zuora__Status__c ='Active';
            zs.InstanceId__c = a.id;
            insert zs;
        
                       
            
      
           

       Test.startTest();
       BatchInstanceExpiryUpdater bieu= new  BatchInstanceExpiryUpdater();
       Database.executeBatch(bieu);
       Test.stopTest();

       
       
    }
    
     static testmethod void test2() {
        
      
       KayakoMetricsKey__c kmk = new KayakoMetricsKey__c();
       kmk.name = 'test';
       kmk.key__c = 'testing';
       insert kmk;
       
       KayakoAuditorKey__c km = new KayakoAuditorKey__c();
       km.name = 'tester';
       km.key__c = 'testing123';
       insert km;
       
       List<Instance__c> aList = new List<Instance__c>();
       
            Instance__c a = new Instance__c();
            a.name='test.instance.com';
            a.uuid__c ='fhjk373374fhfjdkshfjks';
            a.Expiry_Date__c = DateTime.Now();
            a.instance_id__c = 444;
            insert a;
        
             
           
           
        
           Account acc = new Account();
           acc.name = 'test';
           insert acc ;
        
           Opportunity o = new Opportunity();
           o.Name = 'test';
           o.accountId =  acc.id;
           o.StageName = 'Value Proposition';
           o.CloseDate = Date.today()+30;
           o.Instance__c = a.id;
           o.type = 'New Business';
           insert o;
        
          
        
                       
            
      
           

       Test.startTest();
       BatchInstanceExpiryUpdater bieu= new  BatchInstanceExpiryUpdater();
       Database.executeBatch(bieu);
       Test.stopTest();

       
       
    }
}