src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <formula>Subscription__r.Instance_Expiry_Date__c</formula>
        <label>Expiry Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <formula>Subscription__r.Product_Name__r.Name</formula>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SecurityToken__c</fullName>
        <label>Security Token</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DirOutput/objects/Instance__c.object
<CustomObject>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>InstanceId__c</fullName>
        <formula>TEXT(Instance_ID__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Instance ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Instance</label>
    <nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Instance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Instance</label>
        <referenceTo>Instance__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>Kayako 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Kayako 4 OnDemand)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Kayako 3 -&gt; 4 OnDemand)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Kayako 4 (July 2014))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (July 2016)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Download Perpetual Upgrade (July 2016))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Nov 2016)</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Download Perpetual Upgrade (Nov 2016))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 4 (Download Perpetual to Subscription (Dec 2016))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 4 Renewals (Nov 2010)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 4 Renewals (April 2013)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 4 OnDemand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 4 (July 2014)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 3 -&gt; 4 Renewals (Nov 2010)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 3 -&gt; 4 OnDemand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Kayako 4 (Download Perpetual to Subscription (Dec 2016)))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (June 2017)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Download Perpetual Upgrade (June 2017))</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DirOutput/classes/QuoteCreationControllerTest.cls
@isTest
public class QuoteCreationControllerTest{
    
public static testMethod void positiveScenario(){    
    
    
    Account acc = new Account();
    acc.Name = 'test';
    insert acc;
    
    Opportunity o = new Opportunity();
    o.name = 'test';
    o.stageName = 'Proposal and Quote';
    o.closeDate = Date.Today();
    o.accountId = acc.id;
    insert o;
    
    ApexPages.StandardController sc = new ApexPages.StandardController(o);
    QuoteCreationController qc = new QuoteCreationController(sc);
    
    qc.proceed();
}


public static testMethod void negativeScenario(){    
    
    
    Account acc = new Account();
    acc.Name = 'test';
    insert acc; 
    
    Instance__c i = new Instance__c();
    i.name = 'test.kayako.com';
    i.Expiry_Date__c = date.today()-30;
    i.UUID__c = '23434234523456456';
    insert i ;
    
    Opportunity o = new Opportunity();
    o.name = 'test';
    o.stageName = 'Proposal and Quote';
    o.closeDate = Date.Today();
    o.accountId = acc.id;
    o.Instance__c = i.id;
    insert o;
    
    zqu__Quote__c zq = new zqu__Quote__c();
    zq.zqu__Opportunity__c =o.id;
    zq.SecurityToken__c='sc';
    zq.InstanceId__c=123;
    insert zq;
    
    Zuora__CustomerAccount__c zca = new Zuora__CustomerAccount__c();
    zca.Zuora__Account__c = acc.id;
    insert zca;
    
    ApexPages.StandardController sc = new ApexPages.StandardController(o);
    QuoteCreationController qc = new QuoteCreationController(sc);
    
    qc.proceed();
}
    
    
public static testMethod void negativeScenario2(){    
    
    
    Account acc = new Account();
    acc.Name = 'test';
    insert acc;
    
    
    Instance__c i = new Instance__c();
    i.name = 'test.kayako.com';
    i.Expiry_Date__c = date.today();
    i.UUID__c = '23434234523456456';
    i.State__c = 'DELETED';
    insert i ;
    
    Opportunity o = new Opportunity();
    o.name = 'test';
    o.stageName = 'Proposal and Quote';
    o.closeDate = Date.Today();
    o.accountId = acc.id;
    o.Product__c = 'Kayako 4 Upgrade';
    insert o;
    
    zqu__Quote__c zq = new zqu__Quote__c();
    zq.zqu__Opportunity__c =o.id;
    zq.SecurityToken__c='sc';
    zq.InstanceId__c=123;
    insert zq;
    
    Zuora__CustomerAccount__c zca = new Zuora__CustomerAccount__c();
    zca.Zuora__Account__c = acc.id;
    insert zca;
    
    ApexPages.StandardController sc = new ApexPages.StandardController(o);
    QuoteCreationController qc = new QuoteCreationController(sc);
    
    qc.proceed();
}
    

}