src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <formula>Subscription__r.Product_Name__r.Name</formula>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>infer3__Infer_Rating__c</fullName>
        <formula>TRIM(SUBSTITUTE(MID(CASE(FLOOR(infer3__Score_Index__c/255),0,infer3__Score_Object_ID__r.infer3__Rating_0__c,1,infer3__Score_Object_ID__r.infer3__Rating_1__c,2,infer3__Score_Object_ID__r.infer3__Rating_2__c,3,infer3__Score_Object_ID__r.infer3__Rating_3__c,4,infer3__Score_Object_ID__r.infer3__Rating_4__c,5,infer3__Score_Object_ID__r.infer3__Rating_5__c,6,infer3__Score_Object_ID__r.infer3__Rating_6__c,null),1+MOD(infer3__Score_Index__c,255),1),&apos;^&apos;,&apos; &apos;))</formula>
        <label>Infer: Fit Score</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>infer3__Infer_Score__c</fullName>
        <formula>VALUE(TRIM(SUBSTITUTE(MID(CASE(FLOOR(infer3__Score_Index__c/85),0,infer3__Score_Object_ID__r.infer3__Score_0__c,1,infer3__Score_Object_ID__r.infer3__Score_1__c,2,infer3__Score_Object_ID__r.infer3__Score_2__c,3,infer3__Score_Object_ID__r.infer3__Score_3__c,4,infer3__Score_Object_ID__r.infer3__Score_4__c,5,infer3__Score_Object_ID__r.infer3__Score_5__c,6,infer3__Score_Object_ID__r.infer3__Score_6__c,7,infer3__Score_Object_ID__r.infer3__Score_7__c,8,infer3__Score_Object_ID__r.infer3__Score_8__c,9,infer3__Score_Object_ID__r.infer3__Score_9__c,10,infer3__Score_Object_ID__r.infer3__Score_10__c,11,infer3__Score_Object_ID__r.infer3__Score_11__c,12,infer3__Score_Object_ID__r.infer3__Score_12__c,13,infer3__Score_Object_ID__r.infer3__Score_13__c,14,infer3__Score_Object_ID__r.infer3__Score_14__c,15,infer3__Score_Object_ID__r.infer3__Score_15__c,16,infer3__Score_Object_ID__r.infer3__Score_16__c,17,infer3__Score_Object_ID__r.infer3__Score_17__c,18,infer3__Score_Object_ID__r.infer3__Score_18__c,null),1+3*MOD(infer3__Score_Index__c,85),3),&apos;^&apos;,&apos; &apos;)))</formula>
        <label>Infer: Fit Score [0-100]</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>infer3__Infer_Rating__c</fullName>
        <formula>TRIM(SUBSTITUTE(MID(CASE(FLOOR(infer3__Score_Index__c/255),0,infer3__Score_Object_ID__r.infer3__Rating_0__c,1,infer3__Score_Object_ID__r.infer3__Rating_1__c,2,infer3__Score_Object_ID__r.infer3__Rating_2__c,3,infer3__Score_Object_ID__r.infer3__Rating_3__c,4,infer3__Score_Object_ID__r.infer3__Rating_4__c,5,infer3__Score_Object_ID__r.infer3__Rating_5__c,6,infer3__Score_Object_ID__r.infer3__Rating_6__c,null),1+MOD(infer3__Score_Index__c,255),1),&apos;^&apos;,&apos; &apos;))</formula>
        <label>Infer: Fit Score</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>infer3__Infer_Score__c</fullName>
        <formula>VALUE(TRIM(SUBSTITUTE(MID(CASE(FLOOR(infer3__Score_Index__c/85),0,infer3__Score_Object_ID__r.infer3__Score_0__c,1,infer3__Score_Object_ID__r.infer3__Score_1__c,2,infer3__Score_Object_ID__r.infer3__Score_2__c,3,infer3__Score_Object_ID__r.infer3__Score_3__c,4,infer3__Score_Object_ID__r.infer3__Score_4__c,5,infer3__Score_Object_ID__r.infer3__Score_5__c,6,infer3__Score_Object_ID__r.infer3__Score_6__c,7,infer3__Score_Object_ID__r.infer3__Score_7__c,8,infer3__Score_Object_ID__r.infer3__Score_8__c,9,infer3__Score_Object_ID__r.infer3__Score_9__c,10,infer3__Score_Object_ID__r.infer3__Score_10__c,11,infer3__Score_Object_ID__r.infer3__Score_11__c,12,infer3__Score_Object_ID__r.infer3__Score_12__c,13,infer3__Score_Object_ID__r.infer3__Score_13__c,14,infer3__Score_Object_ID__r.infer3__Score_14__c,15,infer3__Score_Object_ID__r.infer3__Score_15__c,16,infer3__Score_Object_ID__r.infer3__Score_16__c,17,infer3__Score_Object_ID__r.infer3__Score_17__c,18,infer3__Score_Object_ID__r.infer3__Score_18__c,null),1+3*MOD(infer3__Score_Index__c,85),3),&apos;^&apos;,&apos; &apos;)))</formula>
        <label>Infer: Fit Score [0-100]</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Assigned_SDR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned SDR</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Authority_determined__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Authority determined</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Budget_determined__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Budget determined</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CancelDripFlow__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is used by process builder which sends out emails(Sales drips). This is marked as true whenever lead is going to be converted(from apex code). This signals out the process builder to stop sending emails to converted leads.</description>
        <label>Cancel Drip Flow</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Needs_determined__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Needs determined</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Proposed_Kayako_Plan__c</fullName>
        <label>Proposed Kayako Plan</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Reassigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reassigned_To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Leads2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>The_number_of_seats__c</fullName>
        <defaultValue>0</defaultValue>
        <label>The number of seats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Timeline_determined__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Timeline determined</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>infer3__Infer_Rating__c</fullName>
        <formula>TRIM(SUBSTITUTE(MID(CASE(FLOOR(infer3__Score_Index__c/255),0,infer3__Score_Object_ID__r.infer3__Rating_0__c,1,infer3__Score_Object_ID__r.infer3__Rating_1__c,2,infer3__Score_Object_ID__r.infer3__Rating_2__c,3,infer3__Score_Object_ID__r.infer3__Rating_3__c,4,infer3__Score_Object_ID__r.infer3__Rating_4__c,5,infer3__Score_Object_ID__r.infer3__Rating_5__c,6,infer3__Score_Object_ID__r.infer3__Rating_6__c,null),1+MOD(infer3__Score_Index__c,255),1),&apos;^&apos;,&apos; &apos;))</formula>
        <label>Infer: Fit Score</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>infer3__Infer_Score__c</fullName>
        <formula>VALUE(TRIM(SUBSTITUTE(MID(CASE(FLOOR(infer3__Score_Index__c/85),0,infer3__Score_Object_ID__r.infer3__Score_0__c,1,infer3__Score_Object_ID__r.infer3__Score_1__c,2,infer3__Score_Object_ID__r.infer3__Score_2__c,3,infer3__Score_Object_ID__r.infer3__Score_3__c,4,infer3__Score_Object_ID__r.infer3__Score_4__c,5,infer3__Score_Object_ID__r.infer3__Score_5__c,6,infer3__Score_Object_ID__r.infer3__Score_6__c,7,infer3__Score_Object_ID__r.infer3__Score_7__c,8,infer3__Score_Object_ID__r.infer3__Score_8__c,9,infer3__Score_Object_ID__r.infer3__Score_9__c,10,infer3__Score_Object_ID__r.infer3__Score_10__c,11,infer3__Score_Object_ID__r.infer3__Score_11__c,12,infer3__Score_Object_ID__r.infer3__Score_12__c,13,infer3__Score_Object_ID__r.infer3__Score_13__c,14,infer3__Score_Object_ID__r.infer3__Score_14__c,15,infer3__Score_Object_ID__r.infer3__Score_15__c,16,infer3__Score_Object_ID__r.infer3__Score_16__c,17,infer3__Score_Object_ID__r.infer3__Score_17__c,18,infer3__Score_Object_ID__r.infer3__Score_18__c,null),1+3*MOD(infer3__Score_Index__c,85),3),&apos;^&apos;,&apos; &apos;)))</formula>
        <label>Infer: Fit Score [0-100]</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Authority_determined__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Authority determined</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Budget_determined__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Budget determined</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LeadOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead_Infer_Fit_Score_0_100__c</fullName>
        <label>Lead Infer: Fit Score [0-100]</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lead_Infer_Fit_Score__c</fullName>
        <label>Lead Infer: Fit Score</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Needs_determined__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Needs determined</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <label>Plan</label>
        <picklist>
            <controllingField>Product__c</controllingField>
            <picklistValues>
                <fullName>Fusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Growth</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scale</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>Kayako 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Kayako 4 OnDemand)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Kayako 3 -&gt; 4 OnDemand)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Kayako 4 (July 2014))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (July 2016)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Download Perpetual Upgrade (July 2016))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Nov 2016)</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Download Perpetual Upgrade (Nov 2016))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 4 (Download Perpetual to Subscription (Dec 2016))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 4 Renewals (Nov 2010)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 4 Renewals (April 2013)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 4 OnDemand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 4 (July 2014)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 3 -&gt; 4 Renewals (Nov 2010)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 3 -&gt; 4 OnDemand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Kayako 4 (Download Perpetual to Subscription (Dec 2016)))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (June 2017)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Download Perpetual Upgrade (June 2017))</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Proposed_Kayako_Plan__c</fullName>
        <label>Proposed Kayako Plan</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Reassigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reassigned_To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>The_number_of_seats__c</fullName>
        <defaultValue>0</defaultValue>
        <label>The number of seats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Timeline_determined__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Timeline determined</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>infer3__Infer_Rating__c</fullName>
        <formula>TRIM(SUBSTITUTE(MID(CASE(FLOOR(infer3__Score_Index__c/255),0,infer3__Score_Object_ID__r.infer3__Rating_0__c,1,infer3__Score_Object_ID__r.infer3__Rating_1__c,2,infer3__Score_Object_ID__r.infer3__Rating_2__c,3,infer3__Score_Object_ID__r.infer3__Rating_3__c,4,infer3__Score_Object_ID__r.infer3__Rating_4__c,5,infer3__Score_Object_ID__r.infer3__Rating_5__c,6,infer3__Score_Object_ID__r.infer3__Rating_6__c,null),1+MOD(infer3__Score_Index__c,255),1),&apos;^&apos;,&apos; &apos;))</formula>
        <label>Infer: Fit Score</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ConvertToOpportunityController.cls
public without sharing class ConvertToOpportunityController extends LeadFlowButtonHandler
{    
    public Opportunity opportunity { get; set; }
    public List <SelectOption> allCompetitors { get; set; }
    public List <String> opportunityCompetitors { get; set; }
    public Account acc;
    //public String selectedAccountId{get;set;}
    public String selectedAccountOption{get;set;}
    public Opportunity newOpportunity{get;set;}
    public Boolean showPanel{get;set;}
    public String ac;
    public Integer contactCount{get;set;}
    
    public ConvertToOpportunityController(ApexPages.StandardController controller)
    {
        super(controller);
        opportunity = new Opportunity();
        opportunity.CloseDate = Date.today().addDays(30);
        allCompetitors = GetListOfCompetitors();
        acc = new Account();
        selectedAccountOption ='Existing Account';
        newOpportunity = new Opportunity();
        contactCount = [select count() from contact where email=:lead.email];
        if(contactCount>0){
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.INFO,'A contact already exists. Click'+'<a href="/_ui/search/ui/UnifiedSearchResults?searchType=2&sen=001&sen=00Q&sen=003&sen=00T&sen=005&sen=00U&sen=006&sen=a19&sen=a1k&sen=a1m&sen=00O&str='+lead.email+'">'+'here</a>'+'to check. You might want to link this one to an existing account.');
            ApexPages.addMessage(myMsg);                
        }
    }
    
   
    
    public PageReference ConvertToOpportunity()
    {
        try{
            
            lead l = new lead(id=lead.id);
            l.CancelDripFlow__c = true;
            update l;

            Territory2 leadTerritory = TerritoryDataAccess.GetLeadRegion(lead);

            String role = TerritoryDataAccess.GetUserRole(user, leadTerritory);

            Id currentOwner = lead.OwnerId;
            Id NewOwner;
            // If user is an ADM and does not have a Manager, we cannot assign the lead to
            // anybody. In this case just show them an error so that they can talk to the
            // person responsible for assigning the manager to ADM.

            if (!Test.isRunningTest()) {
                if(role.equals(RoleName.ADM) || role.equals(RoleName.ISM))
                {
                    if(user.ManagerId == null)
                    {
                        lead.addError('You do not have a manager assigned to handle interested leads, therefor the lead cannot be marked as interested.');
                        return Util.RedirectTo(GetLeadId());
                    }
                    If (role.equals(RoleName.ISM)) {
                        NewOwner = lead.OwnerId;
                     //   NewOwner = user.ManagerId;

                    } else {
                        NewOwner = user.ManagerId;
                    }
                    System.debug('user id got is'+NewOwner);
                }
            }

            
            Database.LeadConvert converter = new Database.LeadConvert();

            converter.setLeadId(lead.Id);
            converter.setConvertedStatus(LeadStatus.CONVERTED);
            converter.setDoNotCreateOpportunity(false);
           
            
            if(newOpportunity.accountid!=null){
                account act = new account(id=newOpportunity.accountid,Type='Standard');
                update act;
                converter.setAccountid(newOpportunity.accountid);
            }
            Database.Leadconvertresult conversion = Database.convertLead(converter);
            if(Test.isRunningTest()){
                opportunity.id = conversion.getOpportunityId();
            }
            Id opportunityId = conversion.getOpportunityId();
            System.debug('the opportunity id is'+opportunityid);
            newOpportunity = OpportunityDataAccess.GetOpportunityById(opportunityId);
            
            newOpportunity.StageName   = OpportunityStage.CREATED;
            newOpportunity.Amount      = opportunity.Amount;
            newOpportunity.CloseDate   = opportunity.CloseDate;
            newOpportunity.Type        = opportunity.Type;
            newOpportunity.Plan__c     = opportunity.Plan__c;
            newOpportunity.Product__c  = opportunity.Product__c;
            
            if(!Test.isRunningTest()){
                
                // Update Lead owner as first SDR who worked on Lead
                newOpportunity.LeadOwner__c = lead.Assigned_SDR__c;
                newOpportunity.Reassigned_To__c = lead.Reassigned_To__c;
                System.debug('the new owner is'+newOwner);
                newOpportunity.OwnerId = newOwner;
            
            }
            // Update checklist values to Opportunity from lead
            newOpportunity.Budget_determined__c = lead.Budget_determined__c;
            newOpportunity.Authority_determined__c = lead.Authority_determined__c;
            newOpportunity.Needs_determined__c  = lead.Needs_determined__c;
            newOpportunity.Timeline_determined__c = lead.Timeline_determined__c;
            newOpportunity.The_number_of_seats__c = lead.The_number_of_seats__c;    
            newOpportunity.Proposed_Kayako_Plan__c = lead.Proposed_Kayako_Plan__c;  
            // Update infer score an rank on Opportunity
            newOpportunity.Lead_Infer_Fit_Score__c = lead.infer3__Infer_Rating__c;
            newOpportunity.Lead_Infer_Fit_Score_0_100__c = lead.infer3__Infer_Score__c;
            
            if(lead.infer3__Infer_Rating__c == '' || lead.infer3__Infer_Rating__c == null ||  lead.infer3__Infer_Score__c == null)
            {
                SF_Error_Log__c error = new SF_Error_Log__c();
                error.Class_Name__c ='ConvertToOpportunityController';
                error.Error_Trace__c ='Lead Infer is blank when converting Lead';
                error.Stack_Trace__c = 'NA';
                error.Error_Type__c = 'Lead Infer Score is Blank';
                error.Line_Number__c = 'NA';
                error.Method_Name__c = 'Convert Lead';
                error.Record_List__c = GetLeadId();
                error.User__c = userinfo.getuserid();
                
                insert error;
            }
                
            update newOpportunity;
            if(conversion.getaccountId()!=null){
                List<Lead>leadList = new List<Lead>();
                leadList =[select id,KA_Domain__c from Lead where id=:lead.id limit 1];
                
                if(leadList.size()>0 && leadList!=null){
                    acc.id = conversion.getAccountId();
                    if(leadList[0].KA_Domain__c!=null){ acc.KA_Domain__c = leadList[0].KA_Domain__c;acc.Type='Standard'; }
                    update acc;
                }
            }
            
            SetOpportunityCompetitors(newOpportunity, opportunityCompetitors);

            return Util.RedirectTo(GetLeadId());
        }
        catch(Exception e)
        {
            SF_Error_Log__c error = new SF_Error_Log__c();
            error.Class_Name__c ='ConvertToOpportunityController';
            error.Error_Trace__c =e.getMessage();
            error.Stack_Trace__c = e.getStackTraceString();
            error.Error_Type__c = 'Lead Convert';
            error.Line_Number__c = string.valueOf(e.getLineNumber());
            error.Method_Name__c = 'Convert Lead';
            error.Record_List__c = GetLeadId();
            error.User__c = userinfo.getuserid();
            
            insert error;
            return Util.RedirectTo(GetLeadId());
        }
    }
        
    public List <SelectOption> GetListOfCompetitors()
    {
        return Util.GetPicklistValues(new OpportunityCompetitor(), 'CompetitorName');
    }
    
    public void SetOpportunityCompetitors(Opportunity opportunity, List <String> competitors)
    {
        List <OpportunityCompetitor> opportunityCompetitors = new List <OpportunityCompetitor> ();
        for(String competitorName : competitors)
        {
            OpportunityCompetitor competitor = new OpportunityCompetitor();
            competitor.CompetitorName = competitorName;
            competitor.OpportunityId = opportunity.Id;
            opportunityCompetitors.add(competitor);
        }
        insert opportunityCompetitors;
    }
    
}