src/objects/Instance__c.object
<CustomObject>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Instance_ID__c</fullName>
        <label>Instance ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Instance</label>
    <nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DirOutput/objects/KayakoAuditorKey__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>KayakoAuditorKey</label>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Instance_ID__c</fullName>
        <formula>Instance__r.Instance_ID__c</formula>
        <label>Instance ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Instance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Instance</label>
        <referenceTo>Instance__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KA_ProductType__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>OnDemand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Download</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>KA_Product__c</fullName>
        <label>Product</label>
        <picklist>
            <picklistValues>
                <fullName>Fusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Growth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scale</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>MQL</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SRL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SQL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SDL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/TestBatchExistingCustomerUpdater.cls
@isTest
public class TestBatchExistingCustomerUpdater {
    static testmethod void testScheduleBatchUpdateNetNextChargeAmount(){
        test.startTest();
        ScheduleBatchUpdateNetNextChargeAmount obj = new ScheduleBatchUpdateNetNextChargeAmount();
        test.stopTest();
    }
    static testmethod void testScheduleBatchLifetimeBilledAmountUpdater(){
        test.startTest();
        ScheduleBatchLifetimeBilledAmountUpdater obj = new ScheduleBatchLifetimeBilledAmountUpdater();
        test.stopTest();
    }
    public static testMethod void positiveScenario(){
      
        
        lead l = new lead();
        l.lastname = 'test';
        l.email = 'test@test.com';
        l.company ='test';
        l.stage__c = 'SRL';
        insert l;
        Test.startTest(); //get all the limits back
        
        BatchExistingCustomerUpdater b = new BatchExistingCustomerUpdater(); //call the batch
        
        Database.executeBatch(b);
        
        Test.stopTest(); //out of limit execution block
    } 
    PRIVATE static testmethod void testInstanceSyncHandler() {
        List<Instance__c> aList = new List<Instance__c>();
       
            Instance__c a = new Instance__c();
            a.name='test.instance.com';
            a.uuid__c ='fhjk373379fhfjdkshfjks';
            a.Expiry_Date__c = DateTime.Now();
            a.instance_id__c = 444;
            insert a;


           Lead l = new Lead();
           l.lastName = 'test';
           l.Email = 'test@test.com';
           l.Company = 'test company';
           l.Instance__c = a.id;
           l.ka_product__c = 'Standard';
           insert l;
           
        insert (new KayakoAuditorKey__c(name = 'test', Key__c='12ssssssssssss') );
        Test.startTest(); //get all the limits back
        
        InstanceSyncHandler.handleEvent('fhjk373379fhfjdkshfjks', string.valueOf(DateTime.Now()), l.id, '');
        Test.stopTest(); //out of limit execution block
    }
    PRIVATE static testmethod void testLeadHandler() {
                
                             User userAE = new User(alias = 'standt', 
                                 email='testingkayako@testorg.com', 
                                 emailencodingkey='UTF-8', 
                                 lastname='Testing', languagelocalekey='en_US', 
                                 localesidkey='en_US',
                                 //UserRoleId = csmRoleId[0].Id,
                                 profileid = [Select Id From Profile where Name like 'System administrator' limit 1 ].id, 
                                 timezonesidkey='America/Los_Angeles', 
                                 username='userTest39943232@kayako.com');
                insert userAE;
        Lead l = new Lead(
                    email = 'newlead@mail.com', 
                    CountryCode = 'US', 
                    lastName = 'last name', 
                    firstName = 'first name', 
                    company = 'test company'
                    
                );

                
                l.put('Email', 'kayako.testing@kayako.com');
                l.put('CountryCode', 'US');
                l.put('KA_Product__c','test');
                l.put('KA_ProductType__c','test');
                insert l;
                
        Lead newLead = new Lead(id= l.Id, LeadSource = 'Demo Request', ownerid= userAE.Id);
        Test.startTest(); //get all the limits back
        Map<id, Lead> mapLead = new Map<id, Lead>();
        mapLead.put(l.Id, newLead);
        LeadTriggerHandler.handleBeforeInsert(new list<lead>{l}, mapLead);
        LeadTriggerHandler.handleafterInsert(new list<lead>{l}, mapLead);
        LeadTriggerHandler.handleBeforeupdate(new list<lead>{l}, mapLead);
        LeadTriggerHandler.handleafterupdate(new list<lead>{l}, mapLead);
        Test.stopTest(); //out of limit execution block
    }
    private static testmethod void testErrorlog() {
        try{
            insert new Lead();
        }
        catch(exception e) {
            SF_LogError.logError(e);
        }
    }
}