src/objects/Instance__c.object
<CustomObject>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>DateTime</type>
    </fields>
    <label>Instance</label>
    <nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>ExpiryEmailSent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is used by process builder to stop multiple trial expiry emails to be sent after the trial has expired.</description>
        <label>Expiry email sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Instance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Instance</label>
        <referenceTo>Instance__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KA_Product__c</fullName>
        <label>Product</label>
        <picklist>
            <picklistValues>
                <fullName>Fusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Growth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scale</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SLA_Breached__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SLA Breached</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/BatchLeadTrialExpiryEmail.cls
global class BatchLeadTrialExpiryEmail implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext BC) {
        
        
        
        String query = 'select id from Instance__c where Expiry_Date__c=TODAY limit 10 '; //string to collect the expired trials.
        
        return Database.getQueryLocator(query);
    }
   
    global void execute(Database.BatchableContext BC, List<Instance__c> scope) {
        
        List<id>leadList = new List<id>(); //converting the scope list (object list) into list of ids.
        for(Lead l: [select id,name,Instance__c,ExpiryEmailSent__c,isconverted,KA_Product__c from lead where ExpiryEmailSent__c=false and isConverted=false and Instance__c IN:scope]){
            leadList.add(l.id);
        }
        
        EmailUtilLeadTrialExpiry.mailSender(leadList);
        
        List<lead>lList = new List<lead>();
        for(lead l :[select id,ExpiryEmailSent__c from lead where id IN:leadList]){
            l.ExpiryEmailSent__c=true;
            l.SLA_Breached__c = true;
            lList.add(l);
        }
        update lList;
    }   
    
    global void finish(Database.BatchableContext BC) {
    }
}