src/objects/Instance__c.object
<CustomObject>
    <label>Instance</label>
    <nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Instance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Instance</label>
        <referenceTo>Instance__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KA_Product__c</fullName>
        <label>Product</label>
        <picklist>
            <picklistValues>
                <fullName>Fusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Growth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scale</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>MQL</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SRL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SQL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SDL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Trial_Expiry_Date__c</fullName>
        <formula>Instance__r.Expiry_Date__c</formula>
        <label>Trial Expiry Date</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/BatchUpdateStatusOnLeads.cls
//******************************************************************
// Name: BatchUpdateStatusOnLeads
// Purpose: This is a batch which updates Trial leads 
// Author: sruti Srivastava
// Date: 27/09/2018 
//******************************************************************
global class BatchUpdateStatusOnLeads implements Database.Batchable<sObject>,Database.AllowsCallouts {
    
    //QUerying trials leads with 22 days of post expiry 
    global Database.QueryLocator start(Database.BatchableContext BC) {
        
        Date date22DaysfromToday = Date.today().addDays(-22);
        String query = 'select Id,Name,KA_Product__c,isConverted,Instance__c from Lead where LeadSource != \'Demo Requested\' '+
                        ' AND LeadSource != \'Webinar\' AND LeadSource != \'Kayako Demo\' '+
                        ' AND Status!= \'Expired Trial\'  AND Trial_Expiry_Date__c <= :date22DaysfromToday and isConverted = false';
        return Database.getQueryLocator(query);  
    }
    
    global void execute(Database.BatchableContext BC, List<Lead> scope) { 
      
        Map<Id,Lead> mapLead = new Map<Id, Lead>();
        List<User> users = [select id FROm USER where name like 'Hamzah Tariq%' limit 1];
        
        //Querying assigning Owner as hamzah and setting up stage as MQL
        for(Lead l:  scope){
            l.Status= 'Expired Trial';
            l.OwnerId = (users != null && users.size() > 0 )?users[0].Id:l.OwnerId;
            l.Stage__c= 'MQL';
            mapLead.put(l.id,l);
        }
        if(!mapLead.isEmpty())  
            update mapLead.values();
    } 
      
    global void finish(Database.BatchableContext BC) {
    }    
}