src/objects/Instance__c.object
<CustomObject>
    <fields>
        <fullName>Instance_ID__c</fullName>
        <label>Instance ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Instance</label>
    <nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DirOutput/objects/KayakoAuditorKey__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>KayakoAuditorKey</label>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Instance_ID__c</fullName>
        <formula>Instance__r.Instance_ID__c</formula>
        <label>Instance ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Instance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Instance</label>
        <referenceTo>Instance__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/EmailTemplateHandler_Test.cls
@isTest
public class EmailTemplateHandler_Test{
    
    public static testMethod void positiveScenario(){
        
        KayakoAuditorKey__c kak = new KayakoAuditorKey__c();
        kak.name = 'test';
        kak.key__c = 'test';
        insert kak;
        
        Instance__c i = new Instance__c();
        i.name = 'test.kayako.com';
        i.instance_id__c = 22233;
        insert i;
        
        Lead l = new Lead();
        l.lastname = 'test';
        l.email = 'test@test.com';
        l.company = 'test';
        l.instance__c = i.id;
        insert l;
        
       Test.setCurrentPageReference(new PageReference('Page.emailtemplate'));
       System.currentPageReference().getParameters().put('id', i.id);
       System.currentPageReference().getParameters().put('type', 'enable');
         

        
            
        EmailTemplateHandler et = new EmailTemplateHandler();
       
    }
    
    
    public static testMethod void negativeScenario(){
        
        KayakoAuditorKey__c kak = new KayakoAuditorKey__c();
        kak.name = 'test';
        kak.key__c = 'test';
        insert kak;
        
        Instance__c i = new Instance__c();
        i.name = 'test.kayako.com';
        i.instance_id__c = 22233;
        insert i;
        
        Lead l = new Lead();
        l.lastname = 'test';
        l.email = 'test@test.com';
        l.company = 'test';
        l.instance__c = i.id;
        insert l;
        
       Test.setCurrentPageReference(new PageReference('Page.emailtemplate'));
       System.currentPageReference().getParameters().put('id', i.id);
       System.currentPageReference().getParameters().put('type', 'disable');
         

        
            
        EmailTemplate et = new EmailTemplate();
       
    }

}