src/objects/Instance__c.object
<CustomObject>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>DateTime</type>
    </fields>
    <label>Instance</label>
    <nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Instance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Instance</label>
        <referenceTo>Instance__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KA_ProductType__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>OnDemand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Download</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>KA_Product__c</fullName>
        <label>Product</label>
        <picklist>
            <picklistValues>
                <fullName>Fusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Growth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scale</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>KA_TrialExpiryDate__c</fullName>
        <label>Trial Expiry Date ka</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/TestInstanceAndLead.cls
@isTest
public class TestInstanceAndLead{

static testMethod void testScenario(){
    lead l = new lead();
    l.lastname = 'test';
    l.company ='test';
    l.email = 'test@test.com';
    l.KA_Product__c = 'test';
    l.KA_ProductType__c ='test';
    insert l;
    
    lead l2 = new lead();
    l2.lastname='test';
    l2.email = 'test@test.com';
    l2.company='test';
    l2.KA_Product__c = 'test';
    l2.KA_ProductType__c ='test';
    insert l2;
    
   
    Instance__c i = new Instance__c();
    i.id = l.Instance__c;
    i.Expiry_Date__c = date.today();
    insert i;
   
   
    lead l3 = new lead();
    l3.lastname='test';
    l3.email = 'test1@test.com';
    l3.company='test';
    l3.KA_TrialExpiryDate__c= date.today();
    l3.instance__c=i.id;
    l3.KA_Product__c = 'test';
    l3.KA_ProductType__c ='test';
    insert l3;
    
    l3.KA_TrialExpiryDate__c=date.today()+1;
    update l3;
    

}


}