src/objects/Instance__c.object
<CustomObject>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Instance</label>
    <nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Authority__c</fullName>
        <label>Authority</label>
        <picklist>
            <picklistValues>
                <fullName>Unanswered</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Decision Maker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Evaluator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Influencer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supporting Evaluator</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Budgeted__c</fullName>
        <label>Budgeted</label>
        <picklist>
            <picklistValues>
                <fullName>Unanswered</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CurrentSystem__c</fullName>
        <label>Current System</label>
        <picklist>
            <picklistValues>
                <fullName>Unanswered</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Nothing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Older Kayako Version</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shared Inbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home grown system</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Another Helpdesk</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Instance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Instance</label>
        <referenceTo>Instance__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KA_Product__c</fullName>
        <label>Product</label>
        <picklist>
            <picklistValues>
                <fullName>Fusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Growth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scale</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>KA_Territory__c</fullName>
        <label>Territory</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Unanswered</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>CEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Founder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agent/Executive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>MQL</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SRL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SQL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SDL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UsedFor__c</fullName>
        <label>Need</label>
        <picklist>
            <picklistValues>
                <fullName>Unanswered</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Internal stakeholder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer support</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/LeadButtonRenderer.cls
public without sharing class LeadButtonRenderer extends LeadFlowButtonHandler
{
    private ApexPages.StandardController leadController;
    
    public LeadButtonRenderer(ApexPages.StandardController controller)
    {
        super(controller);
        leadController = controller;
    }

    public boolean GetCanAcceptOpenLead()
    {
        return LeadStage.MQL.equals(lead.Stage__c) && LeadStatus.OPEN.equals(lead.Status);
    }

    public boolean GetCanUpgrade()
    {
        
        List<lead>lList = new List<lead>();
        lList = [select id,name, Instance__c,Instance__r.state__c,Instance__r.Expiry_Date__c from  lead where (KA_Product__c = 'Growth' OR KA_Product__c = 'Enterprise' OR KA_Product__c= 'Standard' OR KA_Product__c = 'Loyalty' OR  KA_Product__c = 'Inbox' OR KA_Product__c = 'Free' OR KA_Product__c = 'Team' OR KA_Product__c = 'Scale') AND id =:lead.id limit 1];
        if(llist!=null && llist.size()>0 && llist[0].instance__c!=null && llist[0].Instance__r.state__c!='DELETED' && llist[0].Instance__r.Expiry_Date__c>=Date.today()-1){
            return true;
        }else{
            return false;
        }
            
        
        
         
    }

    public boolean GetCanRejectOpenLead()
    {
        return LeadStage.MQL.equals(lead.Stage__c) && LeadStatus.OPEN.equals(lead.Status);
    }

    public boolean GetCanMarkLeadContacted()
    {
        return LeadStage.SAL.equals(lead.Stage__c) && LeadStatus.OPEN.equals(lead.Status);
    }

    public boolean GetCanSetTerritory()
    {
        return LeadStage.SAL.equals(lead.Stage__c) && lead.KA_Territory__c == null;
    }

    public boolean GetCanQualifyLead()
    {
        return LeadStage.SAL.equals(lead.Stage__c) && LeadStatus.CONTACTED.equals(lead.Status);
    }

    public boolean GetCanEnrichLead()
    {
        return LeadStage.SAL.equals(lead.Stage__c) && LeadStatus.CONTACTED.equals(lead.Status);
    }

    public boolean GetCanUpdateContact()
    {
        return LeadStage.SAL.equals(lead.Stage__c) && (
            LeadStatus.OPEN.equals(lead.Status) ||
            LeadStatus.CONTACTED.equals(lead.Status) || LeadStatus.UNRESPONSIVE.equals(lead.Status)
        );
    }

    public boolean GetCanMarkLeadInterested()
    {
        Territory2 leadTerritory = null;
        
        try
        {
            leadTerritory = TerritoryDataAccess.GetLeadRegion(lead);
        }
        catch(UnderflowException noRegionByLeadCountry)
        {
            return false;
        }
        
        String userRole = TerritoryDataAccess.GetUserRole(user, leadTerritory);
        
        Boolean UserHasNoManager = user.ManagerId == null;

        if(RoleName.ADM.equals(userRole) && UserHasNoManager) return false;

        return LeadStatus.CONTACTED.equals(lead.Status) &&
                LeadStage.SAL.equals(lead.Stage__c);
    }

    public boolean GetCanMarkLeadUnresponsive()
    {
        return LeadStage.SAL.equals(lead.Stage__c) && (LeadStatus.OPEN.equals(lead.Status) || LeadStatus.CONTACTED.equals(lead.Status));
    }

    public boolean GetCanMarkLeadResponsive()
    {
        return LeadStage.SAL.equals(lead.Stage__c) && LeadStatus.UNRESPONSIVE.equals(lead.Status);
    }

    public boolean GetCanRejectAcceptedLead()
    {
        Set <String> requiredStatus = new Set <String> { LeadStatus.CONTACTED, LeadStatus.UNRESPONSIVE,LeadStatus.OPEN };
        return LeadStage.SAL.equals(lead.Stage__c) && requiredStatus.contains(lead.Status);
    }

    public boolean GetCanAcceptInterestedLead()
    {
        Territory2 leadTerritory = null;
        
        try
        {
            leadTerritory = TerritoryDataAccess.GetLeadRegion(lead);
        }
        catch(UnderflowException noRegionByLeadCountry)
        {
            return false;
        }
        
        return LeadStage.SAL.equals(lead.Stage__c) && LeadStatus.INTERESTED.equals(lead.Status) && SeniorRoles().contains(TerritoryDataAccess.GetUserRole(user, leadTerritory));
    }

    public boolean GetCanRejectInterestedLead()
    {
        Territory2 leadTerritory = null;
        
        try
        {
            leadTerritory = TerritoryDataAccess.GetLeadRegion(lead);
        }
        catch(UnderflowException noRegionByLeadCountry)
        {
            return false;
        }
        
        return LeadStage.SAL.equals(lead.Stage__c) && LeadStatus.INTERESTED.equals(lead.Status) && SeniorRoles().contains(TerritoryDataAccess.GetUserRole(user, leadTerritory));
    }

    public boolean GetCanReturnInterestedLead()
    {
        Territory2 leadTerritory = null;
        
        try
        {
            leadTerritory = TerritoryDataAccess.GetLeadRegion(lead);
        }
        catch(UnderflowException noRegionByLeadCountry)
        {
            return false;
        }

        return LeadStage.SAL.equals(lead.Stage__c) && LeadStatus.INTERESTED.equals(lead.Status) && SeniorRoles().contains(TerritoryDataAccess.GetUserRole(user, leadTerritory));
    }

    public boolean GetCanConvertToOpportunity()
    {
        Territory2 leadTerritory = null;
        
        try
        {
            leadTerritory = TerritoryDataAccess.GetLeadRegion(lead);
        }
        catch(UnderflowException noRegionByLeadCountry)
        {
            return false;
        }
        
        return (LeadStage.SQL.equals(lead.Stage__c) || LeadStage.SAL.equals(lead.Stage__c)) && (LeadStatus.QUALIFIED.equals(lead.Status)|| LeadStatus.CONTACTED.equals(lead.Status) || LeadStatus.INTERESTED.equals(lead.Status)) && SeniorRoles().contains(TerritoryDataAccess.GetUserRole(user, leadTerritory));
    }

    public boolean GetCanRejectQualifiedLead()
    {
        Territory2 leadTerritory = null;
        
        try
        {
            leadTerritory = TerritoryDataAccess.GetLeadRegion(lead);
        }
        catch(UnderflowException noRegionByLeadCountry)
        {
            return false;
        }
        
        return LeadStage.SQL.equals(lead.Stage__c) && LeadStatus.QUALIFIED.equals(lead.Status) && SeniorRoles().contains(TerritoryDataAccess.GetUserRole(user, leadTerritory));
    }
    
    public boolean GetCanCloseQualifiedLead()
    {
        Territory2 leadTerritory = null;
        
        try
        {
            leadTerritory = TerritoryDataAccess.GetLeadRegion(lead);
        }
        catch(UnderflowException noRegionByLeadCountry)
        {
            return false;
        }
        
        return LeadStage.SQL.equals(lead.Stage__c) && LeadStatus.QUALIFIED.equals(lead.Status) && SeniorRoles().contains(TerritoryDataAccess.GetUserRole(user, leadTerritory));
    }

    public boolean GetCanUpdateInstanceDetails()
    {
        return LeadStage.SAL.equals(lead.Stage__c) && (LeadStatus.CONTACTED.equals(lead.Status) || LeadStatus.INTERESTED.equals(lead.Status));
    }

    public boolean GetCanReopenLead()
    {
        return (LeadStage.SDL.equals(lead.Stage__c) || LeadStage.SRL.equals(lead.Stage__c)) && (LeadStatus.NURTURE.equals(lead.Status) || LeadStatus.DEAD.equals(lead.Status));
    }
    
    
    public boolean GetQualificationAnsweresAreInvalid()
    {
        if(String.isBlank(lead.Budgeted__c)         || lead.Budgeted__c.equals('Unanswered') || String.isBlank(lead.Role__c)          || lead.Role__c.equals('Unanswered') || String.isBlank(lead.Authority__c)     || lead.Authority__c.equals('Unanswered') || String.isBlank(lead.CurrentSystem__c) || lead.CurrentSystem__c.equals('Unanswered') || String.isBlank(lead.UsedFor__c)       || lead.UsedFor__c.equals('Unanswered') || String.isBlank(lead.Industry)         || lead.Industry.equals('Unanswered'))
        {
            return true;
        }
        
        return false;
    }


    private Set <String> SeniorRoles()
    {
        return new Set <String> { RoleName.ISM, RoleName.MNGR, RoleName.RL,RoleName.ADM };
    }
    
    public boolean GetCanConvertToContact(){
    
     if(lead.Status =='Contacted'){
         return true;
     }else{
         return false;
     
     }
    
    }
    
    public pageReference convertToContact(){
        
        PageReference pg = new PageReference('/apex/converttocontact?id='+lead.id);
        pg.setRedirect(true);
        return pg;
    }
    
    public PageReference reject(){
        PageReference pg = new PageReference('/apex/leadreject?id='+lead.id);
        pg.setRedirect(true);
        return pg;
    }
}