src/objects/Instance__c.object
<CustomObject>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Instance_ID__c</fullName>
        <label>Instance ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Instance</label>
    <nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DirOutput/objects/KayakoAuditorKey__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>KayakoAuditorKey</label>
</CustomObject>

src/objects/KayakoMetricsKey__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Kayako Metrics Key is used to communicate with backend to get the Metrics related to an Instance.</description>
    <fields>
        <fullName>Key__c</fullName>
        <description>This is secret key which is used to communicate with backend in order to get the metrics.</description>
        <label>Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>KayakoMetricsKey</label>
</CustomObject>

src/classes/TestBatchInstanceMetricsUpdater.cls
@isTest
public class TestBatchInstanceMetricsUpdater {
    static testmethod void test() {
        
      
       KayakoMetricsKey__c kmk = new KayakoMetricsKey__c();
       kmk.name = 'test';
       kmk.key__c = 'testing';
       insert kmk;
       
       KayakoAuditorKey__c km = new KayakoAuditorKey__c();
       km.name = 'tester';
       km.key__c = 'testing123';
       insert km;
       
       List<Instance__c> aList = new List<Instance__c>();
       
       for (Integer i=0;i<10;i++) {
            Instance__c a = new Instance__c();
            a.name='test.instance.com';
            a.uuid__c ='fhjk373374fhfjdkshfjks';
            a.Expiry_Date__c = DateTime.Now();
            a.instance_id__c = 444;
           
            aList.add(a);
       }
           insert aList;

       Test.startTest();
       BatchInstanceMetricsUpdater bieu= new  BatchInstanceMetricsUpdater();
       Database.executeBatch(bieu);
       Test.stopTest();

       
       
    }
}