src/objects/Instance__c.object
<CustomObject>
    <label>Instance</label>
    <nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Instance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Instance</label>
        <referenceTo>Instance__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KA_Product__c</fullName>
        <label>Product</label>
        <picklist>
            <picklistValues>
                <fullName>Fusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Growth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scale</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Instance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Instance</label>
        <referenceTo>Instance__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <label>Plan</label>
        <picklist>
            <controllingField>Product__c</controllingField>
            <picklistValues>
                <fullName>Fusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Growth</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scale</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>Kayako 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Kayako 4 OnDemand)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Kayako 3 -&gt; 4 OnDemand)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Kayako 4 (July 2014))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (July 2016)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Download Perpetual Upgrade (July 2016))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Nov 2016)</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Download Perpetual Upgrade (Nov 2016))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 4 (Download Perpetual to Subscription (Dec 2016))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 4 Renewals (Nov 2010)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 4 Renewals (April 2013)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 4 OnDemand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 4 (July 2014)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 3 -&gt; 4 Renewals (Nov 2010)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 3 -&gt; 4 OnDemand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Kayako 4 (Download Perpetual to Subscription (Dec 2016)))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (June 2017)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Download Perpetual Upgrade (June 2017))</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ProductUpdater.cls
public class ProductUpdater {
    
    public Boolean showLead {get;set;}
    public Boolean showOpp {get;set;}
    public String ObjId;
    public String instanceid;
    public List<SelectOption> leadProductOptions{get;set;}
    public Opportunity opp {get;set;}
    public Set<String>productSet;
    public Lead l {get;set;}
    public ProductUpdater(){
            objId = ApexPages.currentPage().getParameters().get('rec');
            instanceid =  ApexPages.currentPage().getParameters().get('Id');
            leadProductOptions = new List<SelectOption>();
            productset = new Set<String>{'Enterprise','Growth','Standard','Free','Inbox','Team','Scale'};
            
            if(objId.startsWith('006')){
                List<Opportunity> oppList = [select id,name,type,product__c,plan__c,instance__r.id from opportunity where id =: objId limit 1];
                
                opp = new opportunity();
                opp.id = objId;
                opp.type = oppList[0].type;
                opp.product__c = oppList[0].product__c;
                opp.plan__c = oppList[0].plan__c;
                showOpp = true;
              
            }else if(objId.startsWith('00Q')){
                showLead = true;
                l = new lead();
                l.id =objId;
                List<Lead> leadList = [select id,ka_product__c,instance__r.id from lead where id =: objId limit 1];
                l.ka_product__c = leadlist[0].ka_product__c;
                Schema.DescribeFieldResult fieldResult = lead.ka_product__c.getDescribe();
                List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        
                   for( Schema.PicklistEntry f : ple)
                   {
                      if(productSet.contains(f.getLabel())){
                      leadProductOptions.add(new SelectOption(f.getLabel(), f.getValue()));
                      }
                   }       
            }
    
         
    }
    
    public pageReference updateOpp(){
        pageReference pg = new pageReference('/apex/instancesync?id='+instanceid+'&rec='+objId);
        if(opp.type!='New Business' && opp.type!='Existing - K4 to Kayako'){
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Opportunity type is not valid, allowed values are only New Business and Existing K4 to Kayako');
            ApexPages.addMessage(myMsg);
            return null;
            
        }else if(!opp.product__c.startsWith('Kayako (')){
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Opportunity Product is not valid, product should start with Kayako (');
            ApexPages.addMessage(myMsg);
            return null;
        
        }else{
            update opp;
            return pg;
        }
        
        
        
        
    }
    
    public pageReference updateLead(){
        pageReference pg = new pageReference('/apex/instancesync?id='+instanceId+'&rec='+objId);
            
            update l;
            return pg;
        }
        
    public pageReference cancel(){
        pageReference pg = new PageReference('/'+objId);
        return pg;
    }    
        
        
    }