src/objects/Instance__c.object
<CustomObject>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>InstanceId__c</fullName>
        <formula>TEXT(Instance_ID__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Instance ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Instance_ID__c</fullName>
        <label>Instance ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Seats__c</fullName>
        <label>Instance Seats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Instance</label>
    <nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestBatchSubscriptionInstanceUpdater.cls
@isTest
public class TestBatchSubscriptionInstanceUpdater{
    
    static  testMethod  void positiveScenario(){
        
        Instance__c i = new Instance__c();
        i.Name = 'test.kayako.com';
        i.Expiry_Date__c = Date.today()+30;
        i.Instance_ID__c = 2234;
        i.Seats__c = 23;
        insert i;
        
        Zuora__Subscription__c zs = new Zuora__Subscription__c();
        zs.InstanceId__c = '2234';
        insert zs;    
    
        Test.startTest();
        BatchSubscriptionInstanceUpdater b = new BatchSubscriptionInstanceUpdater();
        Database.executeBatch(b);
        Test.stopTest();
    }


}