src/objects/KayakoMetricsKey__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Kayako Metrics Key is used to communicate with backend to get the Metrics related to an Instance.</description>
    <fields>
        <fullName>Key__c</fullName>
        <description>This is secret key which is used to communicate with backend in order to get the metrics.</description>
        <label>Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>KayakoMetricsKey</label>
</CustomObject>

src/classes/TestScheduleBatchInstanceMetricsUpdater.cls
/*
    This class schedules the Batch Instance Metrics Updater, which in turn runs the batch over the instances.
*/

@isTest
public class TestScheduleBatchInstanceMetricsUpdater  {
    
    static  testMethod void TestSchedule(){
       
       KayakoMetricsKey__c kmk = new KayakoMetricsKey__c();
       kmk.name = 'test';
       kmk.key__c = 'testing';
       insert kmk;
       
       
       
       String chron1 = '0 2 * * * ? *';      
       System.schedule('ScheduleBatchInstanceMetricsUpdater', chron1, new ScheduleBatchInstanceMetricsUpdater());
    
    }



}