src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>IsResponded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsResponded</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KA_ProductType__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>OnDemand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Download</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>KA_Product__c</fullName>
        <label>Product</label>
        <picklist>
            <picklistValues>
                <fullName>Fusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Growth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scale</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SLA_Breached__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SLA Breached</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>MQL</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SRL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SQL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SDL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Plan__c</fullName>
        <label>Plan</label>
        <picklist>
            <controllingField>Product__c</controllingField>
            <picklistValues>
                <fullName>Fusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Growth</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scale</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>Kayako 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Kayako 4 OnDemand)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Kayako 3 -&gt; 4 OnDemand)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Kayako 4 (July 2014))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (July 2016)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Download Perpetual Upgrade (July 2016))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Nov 2016)</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Download Perpetual Upgrade (Nov 2016))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 4 (Download Perpetual to Subscription (Dec 2016))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 4 Renewals (Nov 2010)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 4 Renewals (April 2013)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 4 OnDemand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 4 (July 2014)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 3 -&gt; 4 Renewals (Nov 2010)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 3 -&gt; 4 OnDemand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Kayako 4 (Download Perpetual to Subscription (Dec 2016)))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (June 2017)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Download Perpetual Upgrade (June 2017))</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DirOutput/objects/Shift_Plan__c.object
<CustomObject>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Shift_Name__c</fullName>
        <label>Shift Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>Time</type>
    </fields>
    <label>Shift Plan</label>
    <nameField>
        <displayFormat>Shift-{0000}</displayFormat>
        <label>Shift Hour Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shift Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Shift__c</fullName>
        <label>Shift</label>
        <picklist>
            <picklistValues>
                <fullName>Shift1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shift2</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>Time</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DirOutput/classes/ConvertToOpportunityControllerTest.cls
@isTest
    public class ConvertToOpportunityControllerTest
    {
        @testSetup static void setup() {
                // Create common test accounts
                Shift_Plan__c obj1 = new Shift_Plan__c( Shift_Name__c = 'Shift1',Start_Time__c= Time.newInstance(0, 0, 0,0),
                                                  End_Time__c = Time.newInstance(11, 59, 59, 59));
                insert obj1;
                Shift_Plan__c obj2 = new Shift_Plan__c( Shift_Name__c = 'Shift2',Start_Time__c= Time.newInstance(12, 0, 0,0),
                                                  End_Time__c = Time.newInstance(23, 59, 59, 59));
                insert obj2;
                User userSDR = new User(alias = 'standt', 
                                         email='testingkayako@testorg.com', 
                                         emailencodingkey='UTF-8', 
                                         lastname='Testing', languagelocalekey='en_US', 
                                         localesidkey='en_US',
                                         Shift__c = 'Shift1',
                                         //UserRoleId = csmRoleId[0].Id,
                                         profileid = [Select Id From Profile where Name like 'Sales Development Representative' limit 1 ].id, 
                                         timezonesidkey='America/Los_Angeles', 
                                         username='usersdr_Leadtest@kayako.com');
                User userSDR1 = new User(alias = 'standt', 
                                         email='testingkayako@testorg.com', 
                                         emailencodingkey='UTF-8', 
                                         lastname='Testing', languagelocalekey='en_US', 
                                         localesidkey='en_US',
                                         Shift__c = 'Shift2',
                                         //UserRoleId = csmRoleId[0].Id,
                                         profileid = [Select Id From Profile where Name like 'Sales Development Representative' limit 1 ].id, 
                                         timezonesidkey='America/Los_Angeles', 
                                         username='usersdr_Leadtest2@kayako.com');
                List<User> listUsers = new list<User>();
                listUsers.add(userSDR1);
                listUsers.add(userSDR);
                insert listUsers;

            }
        public static TestMethod void ConvertToOpportunityTest()
        {
            Test.setMock(HttpCalloutMock.class, new WebhookTest());

            SObject lead = ObjectMocker.mock('Lead');
            lead.put('Email', 'mail@example.com');
            lead.put('Stage__c','Qualified');
            lead.put('KA_Product__c', 'test');
            lead.put('KA_ProductType__c', 'test');
            lead.put('countryCode','IN');
            lead.put('leadsource','Demo Request');
            lead.put('Status','Open');
            
            insert lead;
            
            Lead ld= [Select id, Status,IsResponded__c,SLA_Breached__c from lead where id=:lead.id];
            ld.Status='Qualified';
            ld.IsResponded__c = true;
            ld.SLA_Breached__c = true;
            ld.ownerid= userinfo.getuserid();
            update ld;
            test.startTest();
            ApexPages.currentPage().getParameters().put('id', ld.Id);

            ApexPages.StandardController controller = new ApexPages.StandardController(ld);
            ConvertToOpportunityController handler = new ConvertToOpportunityController(controller);
            
            handler.opportunity.Amount     = 33.5;
            handler.opportunity.Type       = Util.GetPicklistValues(handler.opportunity, 'Type').get(0).getValue();
            handler.opportunity.Plan__c    = Util.GetPicklistValues(handler.opportunity, 'Plan__c').get(0).getValue();
            handler.opportunity.Product__c = Util.GetPicklistValues(handler.opportunity, 'Product__c').get(0).getValue();
            handler.opportunityCompetitors = new List <String> ();
            
            
            PageReference response = handler.ConvertToOpportunity();

            Lead refreshedLead = [SELECT Id, Email, IsConverted, Status 
                        FROM Lead WHERE Id = :lead.Id LIMIT 1];

            System.assert(refreshedLead.IsConverted);
            System.assert(refreshedLead.Status == LeadStatus.CONVERTED);
            
            List<String>compList = new List<String>();
            complist.add('firstComp');
            
            handler.SetOpportunityCompetitors(handler.opportunity,compList);
            test.stopTest();
        }
    }