src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>KA_ProductType__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>OnDemand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Download</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>KA_Product__c</fullName>
        <label>Product</label>
        <picklist>
            <picklistValues>
                <fullName>Fusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Growth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scale</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SDR__c</fullName>
        <description>Name of SDR on basis of Owner or PreviousOwner</description>
        <formula>IF(ISPICKVAL(Stage__c , &apos;SAL&apos;) || ISPICKVAL(Stage__c , &apos;SRL&apos;) || ISPICKVAL(Stage__c , &apos;MQL&apos;), (
  IF(ISPICKVAL(Status, &apos;Interested&apos;), (PreviousOwner__r.FirstName &amp; &quot; &quot; &amp; PreviousOwner__r.LastName), (Owner:User.FirstName &amp; &quot; &quot; &amp; Owner:User.LastName ))
), (
  IF(ISPICKVAL(Stage__c , &apos;SQL&apos;) || ISPICKVAL(Stage__c , &apos;SDL&apos;), (PreviousOwner__r.FirstName &amp; &quot; &quot; &amp; PreviousOwner__r.LastName), null)
))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SDR</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>SDR__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SDR</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DirOutput/classes/ResponeTimeCalculationTest.cls
@isTest
    public class ResponeTimeCalculationTest
    {
        public static TestMethod void LeadInsertTest()
        {
                
                User userAE = new User(alias = 'standt', 
                                 email='testingkayako@testorg.com', 
                                 emailencodingkey='UTF-8', 
                                 lastname='Testing', languagelocalekey='en_US', 
                                 localesidkey='en_US',
                                 //UserRoleId = csmRoleId[0].Id,
                                 profileid = [Select Id From Profile where Name like 'System administrator' limit 1 ].id, 
                                 timezonesidkey='America/Los_Angeles',
                                 SDR__c = true, 
                                 username='userTest343232@kayako.com');
                insert userAE;

                Lead lead = new Lead(
                    email = 'newlead@mail.com', 
                    CountryCode = 'US', 
                    lastName = 'last name', 
                    firstName = 'first name', 
                    company = 'test company'
                    
                );

                
                lead.put('Email', 'kayako.testing@kayako.com');
                lead.put('CountryCode', 'US');
                lead.put('Phone', '+8888888888');
                lead.put('KA_Product__c','test');
                lead.put('KA_ProductType__c','test');
                lead.put('OwnerId',userAE.Id);
                
                insert lead;
                
                lead.Status='Contacted';
                
                update lead;
        }   
    }