src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>DaysInMQL__c</fullName>
        <formula>TODAY()-StageToMQLDate__c</formula>
        <label>Days in MQL</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DaysInSAL__c</fullName>
        <formula>StageToSALDate__c - StageToMQLDate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days in SAL</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DaysInSDL__c</fullName>
        <formula>IF(StageToSALDate__c&gt;StageToSDLDate__c,IF(NOT(ISNULL(StageToSDLDate__c)),StageToSALDate__c-StageToSDLDate__c,0),IF(NOT(ISNULL(StageToSDLDate__c)),Today()-StageToSALDate__c,0))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days in SDL</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DaysInSQL__c</fullName>
        <formula>IF(NOT(ISNULL(StageToSDLDate__c)), (StageToSDLDate__c -  StageToSQLDate__c ), (
IF(IsConverted,  (ConvertedDate - StageToSQLDate__c), 0) 
))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days in SQL</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DaysInSRL__c</fullName>
        <formula>IF(NOT(ISNULL(StageToSRLDate__c)),Today()-StageToSRLDate__c,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days in SRL</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rejected__c</fullName>
        <description>True, if the lead was once rejected</description>
        <formula>IF( NOT(ISBLANK( StageToSRLDate__c )), true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Rejected</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>MQL</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SRL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SQL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SDL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

DirOutput/classes/LeadVisualizerControllerTest.cls
@isTest(SeeAllData = true)
public class LeadVisualizerControllerTest{

static testmethod void mqlTestLead(){
    
    String leadid;
    
    for(leadHistory lh :[select leadid,field,newvalue,oldvalue from leadhistory where id='017100000Iu61RkAQI' ]){
        if(lh.field=='Stage__c'  && lh.newvalue=='MQL'){
            leadid=lh.leadid;
        }
    }
    
    if(leadid!=null){
        List<lead> lList =[select id,Stage__c,Rejected__c,Status,DaysInMQL__c,DaysInSAL__c,DaysInSQL__c,DaysInSRL__c,DaysInSDL__c,ConvertedOpportunityId from lead where Stage__c='MQL'AND id=:leadid limit 1];
        Lead l;    
            if(lList.size()>0 &&lList!=null){
            l=lList[0];
        
        
            PageReference pg = Page.leadvisualizer;
            pg.getParameters().put('id',l.id);
            Test.setCurrentPage(pg);
            
        
            ApexPages.StandardController sc = new ApexPages.StandardController(l);
            LeadVisualizerController lvc = new LeadVisualizerController(sc);
            lvc.ownerOfMQL = 'test';
            lvc.ownerOfSAL = 'test';
            lvc.ownerOfSQL = 'test';
        
        } 
    }
}

static testmethod void salTestLead(){
    
     String leadid;
    
     for(leadHistory lh :[select leadid,field,newvalue,oldvalue from leadhistory where id='017100000Jxvl6AAQQ']){
        if(lh.field=='Stage__c' && lh.oldvalue=='MQL' && lh.newvalue=='SAL'){
            leadid=lh.leadid;
        }
    }

    
    
    if(leadid!=null){
        
        List<lead> lList = [select id,Stage__c,Rejected__c,Status,DaysInMQL__c,DaysInSAL__c,DaysInSQL__c,DaysInSRL__c,DaysInSDL__c,ConvertedOpportunityId from lead where Stage__c='SAL' AND id=:leadid limit 1];
        Lead l;    
            if(lList.size()>0 &&lList!=null){
                l=lList[0];
                PageReference pg = Page.leadvisualizer;
                pg.getParameters().put('id',l.id);
                Test.setCurrentPage(pg);
                
                ApexPages.StandardController sc = new ApexPages.StandardController(l);
                LeadVisualizerController lvc = new LeadVisualizerController(sc);
            }
    }

}

static testmethod void sqlTestLead(){
    
    String leadid;    
     
     for(leadHistory lh :[select leadid,field,newvalue,oldvalue from leadhistory where id='017100000JwB94XAQS']){
        if(lh.field=='Stage__c' && lh.oldvalue=='SAL' && lh.newvalue=='SQL'){
            leadid=lh.leadid;
        }
    }


    if(leadid!=null){
        List<lead> lList = [select id,Stage__c,Rejected__c,Status,DaysInMQL__c,DaysInSAL__c,DaysInSQL__c,DaysInSRL__c,DaysInSDL__c,ConvertedOpportunityId from lead where Stage__c='SQL' AND id=:leadid limit 1];
        Lead l;    
            if(lList.size()>0 &&lList!=null){
                l=lList[0];
        
                PageReference pg = Page.leadvisualizer;
                pg.getParameters().put('id',l.id);
                Test.setCurrentPage(pg);
    
                ApexPages.StandardController sc = new ApexPages.StandardController(l);
                LeadVisualizerController lvc = new LeadVisualizerController(sc);
            }
    }

    }

static testmethod void mqlToSrlTestLead(){
    
    String leadid;    
     
     for(leadHistory lh :[select leadid,field,newvalue,oldvalue from leadhistory where id='017100000Iu5AvKAQU']){
        if(lh.field=='Stage__c' && lh.oldvalue=='MQL' && lh.newvalue=='SRL'){
            leadid=lh.leadid;
        }
    }
    
    if(leadId!=null){
        List<lead> lList = [select id,Stage__c,Rejected__c,Status,DaysInMQL__c,DaysInSAL__c,DaysInSQL__c,DaysInSRL__c,DaysInSDL__c,ConvertedOpportunityId from lead where Stage__c='SRL' AND id=:leadid limit 1];
        Lead l;    
            if(lList.size()>0 &&lList!=null){
                l=lList[0];
                PageReference pg = Page.leadvisualizer;
                pg.getParameters().put('id',l.id);
                Test.setCurrentPage(pg);
    
                ApexPages.StandardController sc = new ApexPages.StandardController(l);
                LeadVisualizerController lvc = new LeadVisualizerController(sc);
            }    
    }

}

static testmethod void salToSrlTestLead(){
    
    String leadid;    
     
     for(leadHistory lh :[select leadid,field,newvalue,oldvalue from leadhistory where id='017100000JwARZMAQ4']){
        if(lh.field=='Stage__c' && lh.oldvalue=='SAL' && lh.newvalue=='SRL'){
            leadid=lh.leadid;
        }
    }
    
    if(leadId!=null){
        List<lead> lList = [select id,Stage__c,Rejected__c,Status,DaysInMQL__c,DaysInSAL__c,DaysInSQL__c,DaysInSRL__c,DaysInSDL__c,ConvertedOpportunityId from lead where Stage__c='SRL' AND id=:leadid limit 1];
        Lead l;  
        if(lList.size()>0 &&lList!=null){
                l=lList[0];
                PageReference pg = Page.leadvisualizer;
                pg.getParameters().put('id',l.id);
                Test.setCurrentPage(pg);
                ApexPages.StandardController sc = new ApexPages.StandardController(l);
                LeadVisualizerController lvc = new LeadVisualizerController(sc);
       } 
    }

}

}