src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>StageToSRLDate__c</fullName>
        <label>Stage to SRL Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>MQL</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SRL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SQL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SDL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StatusLastUpdatedDate__c</fullName>
        <label>Status Last Updated Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StatusToNurtureDate__c</fullName>
        <label>Status to Nurture Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

DirOutput/classes/UnresponsiveLeadCleanerJob.cls
global without sharing class UnresponsiveLeadCleanerJob implements Schedulable
{
	global void execute(SchedulableContext context)
    {
        List <Lead> unresponsiveLeads = LeadDataAccess.GetUnresponsiveLeadsSinceDate(Date.today().addMonths(-1));
        
        RejectLeads(unresponsiveLeads);
    }
    
    private void RejectLeads(List <Lead> unresponsiveLeads)
    {
        for(Lead lead : unresponsiveLeads)
        {
            lead.Status = LeadStatus.NURTURE;
            lead.Stage__c = LeadStage.SRL;
            lead.StageToSRLDate__c = Date.today();
            lead.StatusToNurtureDate__c = Date.today();
            lead.StatusLastUpdatedDate__c = Date.today();
        }
        
        update unresponsiveLeads;
    }
}