src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Assigned_SDR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned SDR</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Authority__c</fullName>
        <label>Authority</label>
        <picklist>
            <picklistValues>
                <fullName>Unanswered</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Decision Maker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Evaluator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Influencer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supporting Evaluator</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Authority_determined__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Authority determined</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Budget_determined__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Budget determined</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Budgeted__c</fullName>
        <label>Budgeted</label>
        <picklist>
            <picklistValues>
                <fullName>Unanswered</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CurrentSystem__c</fullName>
        <label>Current System</label>
        <picklist>
            <picklistValues>
                <fullName>Unanswered</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Nothing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Older Kayako Version</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shared Inbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home grown system</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Another Helpdesk</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <picklist>
            <picklistValues>
                <fullName>Unanswered</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multiple</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Factors__c</fullName>
        <label>Factors</label>
        <picklist>
            <picklistValues>
                <fullName>Regional Issues/Data Residency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timeline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid Contact Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>HubSpot_Inc_Score__c</fullName>
        <label>HubSpot Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>KA_Territory__c</fullName>
        <label>Territory</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KA_TrialExpiryDate__c</fullName>
        <label>Trial Expiry Date ka</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LeadType__c</fullName>
        <label>Lead Type</label>
        <picklist>
            <controllingField>LeadSource</controllingField>
            <picklistValues>
                <fullName>Inbound</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Outbound</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sign up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact Us</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Premigration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Events</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Webinars</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Hunt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Starter Plan</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ManualOwnerChange__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ManualOwnerChange</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Needs_determined__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Needs determined</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OpportunityType__c</fullName>
        <label>Opportunity Type</label>
        <picklist>
            <picklistValues>
                <fullName>New Business</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Existing - Seat Expansion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Existing - Plan Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Existing - K4 to Novo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Existing - K4 Download to K4 OnDemand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Existing - K4 Download to K4 OnDemand: P</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PreviousOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The previous owner of the lead. This field is updated as and when the user of the lead changes, the owner field on lead is set to the new owner and this field is set to the current value of owner field.</description>
        <label>Previous Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposed_Kayako_Plan__c</fullName>
        <label>Proposed Kayako Plan</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Reassigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reassigned_To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Leads2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Unanswered</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>CEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Founder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agent/Executive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StageToSRLDate__c</fullName>
        <label>Stage to SRL Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>MQL</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SRL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SQL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SDL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StatusLastUpdatedDate__c</fullName>
        <label>Status Last Updated Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StatusToContactedDate__c</fullName>
        <label>Status to Contacted Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StatusToNurtureDate__c</fullName>
        <label>Status to Nurture Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StatusToUnresponsiveDate__c</fullName>
        <label>Status to Unresponsive Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>The_number_of_seats__c</fullName>
        <defaultValue>0</defaultValue>
        <label>The number of seats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Timeline_determined__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Timeline determined</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UsedFor__c</fullName>
        <label>Need</label>
        <picklist>
            <picklistValues>
                <fullName>Unanswered</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Internal stakeholder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer support</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>infer3__Infer_Rating__c</fullName>
        <formula>TRIM(SUBSTITUTE(MID(CASE(FLOOR(infer3__Score_Index__c/255),0,infer3__Score_Object_ID__r.infer3__Rating_0__c,1,infer3__Score_Object_ID__r.infer3__Rating_1__c,2,infer3__Score_Object_ID__r.infer3__Rating_2__c,3,infer3__Score_Object_ID__r.infer3__Rating_3__c,4,infer3__Score_Object_ID__r.infer3__Rating_4__c,5,infer3__Score_Object_ID__r.infer3__Rating_5__c,6,infer3__Score_Object_ID__r.infer3__Rating_6__c,null),1+MOD(infer3__Score_Index__c,255),1),&apos;^&apos;,&apos; &apos;))</formula>
        <label>Infer: Fit Score</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>infer3__Infer_Score__c</fullName>
        <formula>VALUE(TRIM(SUBSTITUTE(MID(CASE(FLOOR(infer3__Score_Index__c/85),0,infer3__Score_Object_ID__r.infer3__Score_0__c,1,infer3__Score_Object_ID__r.infer3__Score_1__c,2,infer3__Score_Object_ID__r.infer3__Score_2__c,3,infer3__Score_Object_ID__r.infer3__Score_3__c,4,infer3__Score_Object_ID__r.infer3__Score_4__c,5,infer3__Score_Object_ID__r.infer3__Score_5__c,6,infer3__Score_Object_ID__r.infer3__Score_6__c,7,infer3__Score_Object_ID__r.infer3__Score_7__c,8,infer3__Score_Object_ID__r.infer3__Score_8__c,9,infer3__Score_Object_ID__r.infer3__Score_9__c,10,infer3__Score_Object_ID__r.infer3__Score_10__c,11,infer3__Score_Object_ID__r.infer3__Score_11__c,12,infer3__Score_Object_ID__r.infer3__Score_12__c,13,infer3__Score_Object_ID__r.infer3__Score_13__c,14,infer3__Score_Object_ID__r.infer3__Score_14__c,15,infer3__Score_Object_ID__r.infer3__Score_15__c,16,infer3__Score_Object_ID__r.infer3__Score_16__c,17,infer3__Score_Object_ID__r.infer3__Score_17__c,18,infer3__Score_Object_ID__r.infer3__Score_18__c,null),1+3*MOD(infer3__Score_Index__c,85),3),&apos;^&apos;,&apos; &apos;)))</formula>
        <label>Infer: Fit Score [0-100]</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/LeadDataAccess.cls
public without sharing class LeadDataAccess 
{
    /**
     * @var matchingListsCache Cache leads by email.
     */
    private static Map <String, List <Lead>> matchingListsCache = new Map <String, List<Lead>> ();

    /**
     * @var leadsCache Cache leads by Id
     */
    private static Map <Id, Lead> leadsCache = new Map <Id, Lead> ();

    /**
     * Get matching leads by email.
     * 
     * @param leadToMatch
     * @returns List <Lead>
     * @author Mohammad Gufran <mohammad.gufran@kayako.com>
     */
    public static List <Lead> GetMatchingLeads (Lead leadToMatch)
    {
        if(matchingListsCache.containsKey(leadToMatch.Email))
        {
            return matchingListsCache.get(leadToMatch.Email);
        }
        
        List <Lead> matchingLeads = [Select id,country,leadType__c, CountryCode, OwnerId, CreatedDate 
                                     FROM Lead WHERE (email = :leadToMatch.Email and id != :leadToMatch.Id and KA_Territory__c = :leadToMatch.KA_Territory__c) 
                                     ORDER BY CreatedDate DESC LIMIT 10];
        
        if(matchingLeads.isEmpty()) throw new UnderflowException('No matching lead exists for email ' + leadToMatch.Email);
        
        matchingListsCache.put(leadToMatch.Email, matchingLeads);
        
        return matchingLeads;
    }

    /**
     * Get a lead by its ID
     *
     * @param leadId Id
     * @returns Lead
     * @author Mohammad Gufran <mohammad.gufran@kayako.com>
     */
    public static Lead GetLeadById(Id leadId)
    {
        if(leadsCache.containsKey(leadId))
        {
            return leadsCache.get(leadId);
        }

        try
        {
            Lead lead = [SELECT Id,country, Email,leadType__c,Factors__c,Comments__c, Status, CountryCode, Industry, NumberOfEmployees, OpportunityType__c,
                            Stage__c, KA_Territory__c, HubSpot_Inc_Score__c, Company, KA_TrialExpiryDate__c,
                            StatusToContactedDate__c, Budgeted__c, Role__c, City, PreviousOwner__c,
                            Authority__c, CurrentSystem__c, UsedFor__c, Department__c, OwnerId,
                            State, PostalCode, Phone, MobilePhone, HasOptedOutOfEmail, LeadSource,ManualOwnerChange__c,Reassigned_To__c,Assigned_SDR__c,Budget_determined__c,Authority_determined__c,Needs_determined__c,Timeline_determined__c,The_number_of_seats__c,Proposed_Kayako_Plan__c,infer3__Infer_Rating__c,infer3__Infer_Score__c,
                            (SELECT Title, Body FROM Notes)
                        FROM Lead WHERE Id = :leadId LIMIT 1];

            leadsCache.put(leadId, lead);

            return lead;
        }
        catch(QueryException nullResultException)
        {
            throw new UnderflowException('No lead found by Id ' + leadId);
        }
    }
    
    public static List <Lead> GetUnresponsiveLeadsSinceDate(Date lastResponseTime)
    {
        List <Lead> unresponsiveLeads = new List <Lead> ();
        
        try
        {
            unresponsiveLeads = [SELECT Id,country,LeadType__c,CountryCode, Email, Status, Stage__c, 
                                    OwnerId, StageToSRLDate__c, StatusToNurtureDate__c, 
                                    StatusLastUpdatedDate__c
                                FROM Lead 
                                WHERE Status = 'Unresponsive' 
                                       AND StatusToUnresponsiveDate__c <= :lastResponseTime];
            
            return unresponsiveLeads;
        }
        catch(QueryException nullResultException)
        {
            return unresponsiveLeads;
        }
    }
    
    public static List <Note> GetNotesOnLead(Id leadId)
    {
        List <Note> notes = null;

        try
        {
            notes = [SELECT Title, Body FROM Note WHERE ParentId = :leadId];
        }
        catch(QueryException nullResultException)
        {
            notes = new List <Note> ();
        }
        
        return notes;
    }
}