src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Included_In_Drip_Date__c</fullName>
        <description>This field will hold the date on which the lead was included in the drip.</description>
        <label>Included In Drip Date</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Included_In_Drip_Date__c</fullName>
        <label>Included In Drip Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Lead_ID__c</fullName>
        <label>Lead ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DirOutput/classes/DripEmailTest.cls
@isTest(SeeAllData=true)
public class DripEmailTest {

     static testMethod void positive(){  
         List<id>lList = new List<id>();
         List<id>oList = new List<id>();
         for(lead l :[select id from lead where ownerid!=null and Included_In_Drip_Date__c!=null and isconverted=false limit 1]){
             llist.add(l.id);
         }
         
         for(opportunity o: [select id from opportunity where ownerid!=null and lead_id__c!=null limit 1]){
            olist.add(o.id);      
         }
       
        EmailUtil1Hour.mailSender(llist); 
        EmailUtilOneHourK5.mailSender(llist);
        EmailUtilOneHour.mailSender(llist);
        
        
        EmailUtil168Hours.mailSender(llist);
        
        EmailUtil72Hour.mailSender(llist);
        EmailUtil170Hour2.mailSender(llist);
        EmailUtil336Hour.mailSender(llist);
        
        
        
        
        
        EmailUtil170Hour.mailSender(llist);
        EmailUtilLeadTrialExpiry.mailSender(llist);
        EmailUtilOpportunityTrialExpiry.mailSender(olist);
        EmailUtil600Hour.mailSender(llist);
        EmailUtil48Hour.mailSender(llist);
        
        
        EmailUtil93Hour.mailSender(llist);
        EmailUtil1HourForOpp.mailSender(llist); 
        EmailUtil170HourForOpp.mailSender(llist);
        EmailUtil600HourForOpp.mailSender(llist);
        EmailUtil93HourForOpp.mailSender(llist);
    }
}