src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>KA_ProductType__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>OnDemand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Download</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>KA_Product__c</fullName>
        <label>Product</label>
        <picklist>
            <picklistValues>
                <fullName>Fusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Growth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scale</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StageToSRLDate__c</fullName>
        <label>Stage to SRL Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>MQL</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SRL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SQL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SDL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StatusLastUpdatedDate__c</fullName>
        <label>Status Last Updated Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StatusToNurtureDate__c</fullName>
        <label>Status to Nurture Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StatusToUnresponsiveDate__c</fullName>
        <label>Status to Unresponsive Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/UnresponsiveLeadCleanerJobTest.cls
@IsTest
public class UnresponsiveLeadCleanerJobTest 
{
    public static TestMethod void CleanOldUnresponsiveLeads()
    {
        Test.setMock(HttpCalloutMock.class, new WebhookTest());

        SObject lead = ObjectMocker.mock('Lead');
        lead.put('Status', LeadStatus.UNRESPONSIVE);
        lead.put('StatusToUnresponsiveDate__c', Date.today().addMonths(-3));
        lead.put('Email', 'unresponsive@kayako.test');
        lead.put('KA_Product__c', 'test');
        lead.put('KA_ProductType__c','test');
        
        insert lead;
        
        UnresponsiveLeadCleanerJob job = new UnresponsiveLeadCleanerJob();
        SchedulableContext ctx = null;
        job.execute(ctx);
        
        Lead updatedLead = [SELECT Id, Status, Stage__c, 
                            StageToSRLDate__c, StatusToNurtureDate__c, StatusLastUpdatedDate__c 
                            FROM Lead WHERE Id = :lead.Id and KA_Product__c!=null and KA_ProductType__c!=null LIMIT 1];
        
        System.assertEquals(LeadStatus.NURTURE, updatedLead.Status);
        System.assertEquals(LeadStage.SRL, updatedLead.Stage__c);
        System.assertEquals(Date.today(), updatedLead.StageToSRLDate__c);
        System.assertEquals(Date.today(), updatedLead.StatusToNurtureDate__c);
        System.assertEquals(Date.today(), updatedLead.StatusLastUpdatedDate__c);
    }
}