src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Authority__c</fullName>
        <label>Authority</label>
        <picklist>
            <picklistValues>
                <fullName>Unanswered</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Decision Maker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Evaluator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Influencer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supporting Evaluator</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Budgeted__c</fullName>
        <label>Budgeted</label>
        <picklist>
            <picklistValues>
                <fullName>Unanswered</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CurrentSystem__c</fullName>
        <label>Current System</label>
        <picklist>
            <picklistValues>
                <fullName>Unanswered</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Nothing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Older Kayako Version</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shared Inbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home grown system</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Another Helpdesk</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <picklist>
            <picklistValues>
                <fullName>Unanswered</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multiple</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OpportunityType__c</fullName>
        <label>Opportunity Type</label>
        <picklist>
            <picklistValues>
                <fullName>New Business</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Existing - Seat Expansion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Existing - Plan Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Existing - K4 to Novo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Existing - K4 Download to K4 OnDemand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Existing - K4 Download to K4 OnDemand: P</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Unanswered</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>CEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Founder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agent/Executive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StageToSQLDate__c</fullName>
        <label>Stage to SQL Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StatusToQualifiedDate__c</fullName>
        <label>Status to Qualified Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>UsedFor__c</fullName>
        <label>Need</label>
        <picklist>
            <picklistValues>
                <fullName>Unanswered</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Internal stakeholder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer support</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Authority__c</fullName>
        <description>Mapped with the custom field of lead object to make it visible under Opportunities page</description>
        <label>Authority</label>
        <picklist>
            <picklistValues>
                <fullName>Unanswered</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Decision Maker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Evaluator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Influencer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supporting Evaluator</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Budgeted__c</fullName>
        <description>Mapped with the custom field from Lead object to make it visible in Opportunities</description>
        <label>Budgeted</label>
        <picklist>
            <picklistValues>
                <fullName>Unanswered</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <description>Mapped with the custom field of lead object to make it visible at Opportunities page</description>
        <label>Department</label>
        <picklist>
            <picklistValues>
                <fullName>Unanswered</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multiple</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <description>Mapped with the custom field of lead object to make it visible in the Opportunities page</description>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Unanswered</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>CEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Founder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agent/Executive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/LeadQualificationController.cls
public without sharing class LeadQualificationController extends LeadFlowButtonHandler
{
    public String budgeted { get; set; }
    public String role { get; set; }
    public String authority { get; set; }
    public String currentSystem { get; set; }
    public String intendedUse { get; set; }
    public String department { get; set; }
    public String notes { get; set; }
    public String industry { get; set; }
    public String opportunityType { get; set; }

    public LeadQualificationController(ApexPages.StandardController controller) 
    {
        super(controller);
        budgeted = lead.Budgeted__c;
        role = lead.Role__c;
        authority = lead.Authority__c;
        currentSystem = lead.CurrentSystem__c;
        intendedUse = lead.UsedFor__c;
        department = lead.Department__c;
        opportunityType = lead.OpportunityType__c;
        industry = lead.industry;
        notes = '';
    }

    public PageReference QualifyLead()
    {
        lead.Budgeted__c = budgeted;
        lead.Role__c = role;
        lead.Authority__c = authority;
        lead.CurrentSystem__c = currentSystem;
        lead.UsedFor__c = intendedUse;
        lead.Department__c = department;
        lead.StatusToQualifiedDate__c = Date.today();
        lead.StageToSQLDate__c = Date.today();
        lead.Industry = industry;
        lead.OpportunityType__c = opportunityType;

        update lead;

        if(String.isNotEmpty(notes))
        {
            Note newNote = new Note();
            newNote.Body = notes;
            newNote.Title = 'Notes by ' + UserDataAccess.GetCurrentUser().Name + ' on ' + Date.today().format();
            newNote.ParentId = lead.Id;
            newNote.OwnerId = UserDataAccess.GetCurrentUser().Id;

            insert newNote;
        }

        return Util.RedirectTo(GetLeadId());
    }

    public List <SelectOption> GetBudgetedOptions()
    {
        return Util.GetPicklistValues(lead, 'Budgeted__c');
    }

    public List <SelectOption> GetRoleOptions()
    {
        return Util.GetPicklistValues(lead, 'Role__c');
    }

    public List <SelectOption> GetAuthorityOptions()
    {
        return Util.GetPicklistValues(lead, 'Authority__c');
    }

    public List <SelectOption> GetCurrentSystemOptions()
    {
        return Util.GetPicklistValues(lead, 'CurrentSystem__c');
    }

    public List <SelectOption> GetIntendedUseOptions()
    {
        return Util.GetPicklistValues(lead, 'UsedFor__c');
    }

    public List <SelectOption> GetDepartmentOptions()
    {
        return Util.GetPicklistValues(lead, 'Department__c');
    }
    
    public List <SelectOption> GetIndustryOptions()
    {
        return Util.GetPicklistValues(lead, 'Industry');
    }
    
    public List <SelectOption> GetOpportunityTypeOptions()
    {
        return Util.GetPicklistValues(new Opportunity(), 'Type');
    }
}