src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>CancelDripFlow__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is used by process builder which sends out emails(Sales drips). This is marked as true whenever lead is going to be converted(from apex code). This signals out the process builder to stop sending emails to converted leads.</description>
        <label>Cancel Drip Flow</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsResponded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsResponded</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KA_ProductType__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>OnDemand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Download</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>KA_Product__c</fullName>
        <label>Product</label>
        <picklist>
            <picklistValues>
                <fullName>Fusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Growth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scale</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

DirOutput/classes/convertToContactTest.cls
@isTest
public class convertToContactTest {
    public static testMethod void positiveScenario(){
        lead l = new lead();
        l.lastname = 'test';
        l.Company='test';
        l.Email='s@s.com';
        l.KA_Product__c='test';
        l.KA_ProductType__c='test';
        l.LeadSource = 'Demo Request';
        insert l;
        l.status='Qualified';
        l.IsResponded__c = true;
        l.CancelDripFlow__c=true;
        update l;
        Apexpages.currentpage().getparameters().put('id' , l.Id);
        convertToContact c = new convertToContact();
        
        c.acr.role ='Decision Maker' ;
        
        c.convert();
        
    }
}