src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>KA_ProductType__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>OnDemand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Download</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>KA_Product__c</fullName>
        <label>Product</label>
        <picklist>
            <picklistValues>
                <fullName>Fusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Growth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scale</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/LeadEnrichmentControllerTest.cls
@isTest
public class LeadEnrichmentControllerTest
{
    public static TestMethod void VerifyLeadEnrichment()
    {
        SObject lead = ObjectMocker.mock('Lead');
        lead.put('Email', 'mail@example.com');
        lead.put('NumberOfEmployees', 39);
        lead.put('KA_Product__c','test');
        lead.put('KA_ProductType__c','test');
        insert lead;

        ApexPages.currentPage().getParameters().put('id', lead.Id);

        ApexPages.StandardController controller = new ApexPages.StandardController(lead);
        LeadEnrichmentController handler = new LeadEnrichmentController(controller);

        handler.industry = handler.GetListOfIndustries().get(0).getValue();
        PageReference response = handler.EnrichLead();

        System.assert(response.getRedirect());
    }   
}