src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>KA_TrialExpiryDate__c</fullName>
        <label>Trial Expiry Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <label>Plan</label>
        <picklist>
            <controllingField>Product__c</controllingField>
            <picklistValues>
                <fullName>Fusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Growth</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scale</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>Kayako 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Kayako 4 OnDemand)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Kayako 3 -&gt; 4 OnDemand)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Kayako 4 (July 2014))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (July 2016)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Download Perpetual Upgrade (July 2016))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Nov 2016)</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Download Perpetual Upgrade (Nov 2016))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 4 (Download Perpetual to Subscription (Dec 2016))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 4 Renewals (Nov 2010)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 4 Renewals (April 2013)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 4 OnDemand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 4 (July 2014)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 3 -&gt; 4 Renewals (Nov 2010)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 3 -&gt; 4 OnDemand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Kayako 4 (Download Perpetual to Subscription (Dec 2016)))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (June 2017)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Download Perpetual Upgrade (June 2017))</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/OpportunityDataAccess.cls
public without sharing class OpportunityDataAccess 
{
    private static Map <Id, Opportunity> opportunityCache = new Map <Id, Opportunity> ();

    public static Opportunity GetOpportunityById(Id opportunityId)
    {
        if(opportunityCache.containsKey(opportunityId)) 
        {
            return opportunityCache.get(opportunityId);
        }

        try
        {
            Opportunity opportunity = [SELECT Id, StageName, CloseDate, Amount, Type, KA_TrialExpiryDate__c, Product__c, Plan__c From Opportunity WHERE Id = :opportunityId];

            opportunityCache.put(opportunityId, opportunity);

            return opportunity;
        }
        catch(QueryException noResultFound)
        {
            throw new UnderflowException('Cannot find the opportunity with Id ' + opportunityId);
        }
    }

    public static boolean OpportunityHasQuote(Id opportunityId)
    {
        List <zqu__Quote__c> quotes = [SELECT Id, zqu__Opportunity__c FROM zqu__Quote__c WHERE zqu__Opportunity__c = :opportunityId]; 

        return ! quotes.isEmpty();
    }
    
    public static List <OpportunityHistory> GetHistory(Id opportunityId)
    {
        return [SELECT Amount, CloseDate, CreatedById, CreatedDate,
                ExpectedRevenue, ForecastCategory, Id, IsDeleted, OpportunityId,
                Probability, StageName, SystemModstamp 
                FROM OpportunityHistory 
                WHERE OpportunityId = :opportunityId ORDER BY CreatedDate 
                DESC NULLS FIRST LIMIT 100];
    }
}