src/objects/SF_Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>Class_Name__c</fullName>
        <label>Class Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Trace__c</fullName>
        <label>Error Trace</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Error_Type__c</fullName>
        <label>Error Type</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_Number__c</fullName>
        <label>Line Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Method_Name__c</fullName>
        <label>Method Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SF Error Log</label>
    <nameField>
        <displayFormat>SFERR-{00000000}</displayFormat>
        <label>SF Error Logs No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SF Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SF_LogError.cls
/**
  * ───────────────────────────────────────────────────────────────────────────────────────────────┐
  * Type - Apex Class
  * ────────────────────────────────────────────────────────────────────────────────────────────────
  * @Object      SF Error Log  
  * @Description This class will be used by all the error handling logic to created
  *              Error Log Object in salesforce
  * @Author      Manoj Sankaran
  * ───────────────────────────────────────────────────────────────────────────────────────────────┘
  * Modification Log
  * 09-20-2018 - Created by Manoj Sankaran
  * 
  */
public class SF_LogError{
    public static void logError(Exception e){
            SF_Error_Log__c errorLog = new SF_Error_Log__c();
            //split the trac string to get class name
            string[] trace = e.getStackTraceString().split('\\.');
            errorLog.Class_Name__c = trace[1];
            
            //find the index of the first ':' and then get substring of string to get just the method name and remove unwanted data
            integer indexOfValue = trace[2].indexOf(':');
            errorLog.Method_Name__c = trace[2].substring(0, indexOfValue);
            
            errorLog.Error_Trace__c = e.getMessage();
            errorLog.Line_Number__c = string.valueOf(e.getLineNumber());
            errorLog.Error_Type__c = e.getTypeName();
            errorLog.User__c = userinfo.getFirstname() +' '+userinfo.getLastName();
            insert errorLog; 
    }
}