DirOutput/objects/Instance__c.object
<CustomObject>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>DateTime</type>
    </fields>
    <label>Instance</label>
    <nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ClosedBy__c</fullName>
        <label>ClosedBy</label>
        <picklist>
            <picklistValues>
                <fullName>Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Competitors__c</fullName>
        <label>Competitors</label>
        <picklist>
            <picklistValues>
                <fullName>Desk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Freshdesk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Front</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Help Scout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intercom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not evaluating others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zendesk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HappyFox</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>ContractTerm__c</fullName>
        <label>Contract Term</label>
        <picklist>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bi Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 years+</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Factors__c</fullName>
        <label>Factors</label>
        <picklist>
            <picklistValues>
                <fullName>Regional Issues/Data Residency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self Serve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unresponsive/Timeline</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Instance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Instance</label>
        <referenceTo>Instance__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LostDate__c</fullName>
        <label>Stage To Lost Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Revenue__c</fullName>
        <label>Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>StageToDemoDate__c</fullName>
        <label>Stage To Demo Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StageToNegotiationDate__c</fullName>
        <label>Stage To Negotiation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StageToProposalDate__c</fullName>
        <label>Stage To Proposal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StageToValuePropositionDate__c</fullName>
        <label>Stage To Value Proposition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>WonDate__c</fullName>
        <label>Stage To Won Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DirOutput/classes/OpportunityButtonActionHandler.cls
public without sharing abstract class OpportunityButtonActionHandler 
{
    protected Opportunity opportunity;
    public Opportunity opp {get;set;}
    
    public String lostReason {get; set;}
    public String lostDetails {get;set;}
    public String wonReason {get;set;}
    public String wonDetails {get;set;}
    public String contractTerm {get;set;}
    public Decimal revenue{get;set;}
    public String lostStage{get;set;}
    public String competitors {get;set;}
    public List<SelectOption> lostStageList{get;set;}

    public OpportunityButtonActionHandler()
    {
        opportunity = OpportunityDataAccess.GetOpportunityById(getOpportunityId());
        opp = new opportunity();
        //adding closed lost values to the lost stage list 
        lostStageList = new List<SelectOption>();
        lostStageList.add(new SelectOption('Closed Lost: Dead','Closed Lost: Dead'));
        lostStageList.add(new SelectOption('Closed Lost: Duplicate','Closed Lost: Duplicate'));
        //lostStageList.add(new SelectOption('Closed Lost: Ignored','Closed Lost: Ignored'));
        opp = [select id,name,factors__c,comments__c,competitors__c,contractTerm__c,revenue__c from opportunity where id =:getOpportunityId()];
        
         if(opp!=null){
             wondetails = opp.comments__c;
             wonreason = opp.factors__c;
             contractTerm = opp.ContractTerm__c;
             opportunity.Competitors__c = opp.Competitors__c;
             revenue = opp.Revenue__c;
         }
        
    }

    protected Id getOpportunityId()
    {
        return ApexPages.currentPage().getParameters().get('id');
    }

    public PageReference DemoOpportunity()
    {
        opportunity.StageName = OpportunityStage.DEMO;
        opportunity.StageToDemoDate__c = Date.today();

        update opportunity;

        return Util.RedirectTo(getOpportunityId());
    }

    public PageReference ProjectPostponedOpportunity(){
        opportunity.StageName = OpportunityStage.PROJECT_POSTPONED;

        update opportunity;

        return Util.RedirectTo(getOpportunityId());
    }

    public PageReference ProvideProposalAndQuote()
    {
        opportunity.StageName = OpportunityStage.PROPOSAL_AND_QUOTE;
        opportunity.StageToProposalDate__c = Date.today();

        update opportunity;

        return Util.RedirectTo(getOpportunityId());
    }
    
    
    public PageReference markAsAccept()
    {
        opportunity.StageName = OpportunityStage.VALUE_PROPOSITION;
        opportunity.StageToValuePropositionDate__c = Date.today();

        update opportunity;

        return Util.RedirectTo(getOpportunityId());
    }
    
    
    public PageReference markAsReject()
    {
        opportunity.StageName = OpportunityStage.REJECTED;
        opportunity.LostDate__c = Date.today();

        update opportunity;

        return Util.RedirectTo(getOpportunityId());
    }
    
    
    

    public PageReference MarkAsLost()
    {
        
        if(lostStage == 'Closed Lost: Dead' && (lostReason=='' || lostReason==null)){
            
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Please select factor'));
            
            return null;
        
        }else{
        
        
        
        opportunity.LostDate__c = Date.today();
        opportunity.CloseDate = Date.today();
        opportunity.ClosedBy__c = 'Agent';
        opportunity.factors__c = lostReason;
        opportunity.comments__c = lostDetails;
        opportunity.StageName = lostStage;
        opportunity.Competitors__c = opp.Competitors__c;
        
        
        update opportunity;

        return Util.RedirectTo(getOpportunityId());
        
        }
    }

    public PageReference MarkAsWon()
    {
        opportunity.StageName = OpportunityStage.WON;
        opportunity.WonDate__c = Date.today();
        opportunity.CloseDate = Date.today();
        opportunity.ClosedBy__c = 'Agent';
        opportunity.comments__c = wondetails;
        opportunity.factors__c = wonreason;
        opportunity.ContractTerm__c = opp.contractTerm__c;
        opportunity.Competitors__c = opp.Competitors__c;
        opportunity.Revenue__c=revenue;
        update opportunity;

        return Util.RedirectTo(getOpportunityId());
    }
    
    
    public PageReference UpdateWonReason()
    {
        
        
        opportunity.comments__c = wondetails;
        opportunity.factors__c = wonreason;
        opportunity.ContractTerm__c = opp.contractTerm__c;
        opportunity.Competitors__c = opp.Competitors__c;
        opportunity.Revenue__c=revenue;
        update opportunity;

        return Util.RedirectTo(getOpportunityId());
    }

    public PageReference ReviewAndNegotiate()
    {
        opportunity.StageName = OpportunityStage.REVIEW_AND_NEGOTIATION;
        Opportunity.StageToNegotiationDate__c = Date.today();

        update opportunity;

        return Util.RedirectTo(getOpportunityId());
    }
    
    public List <SelectOption> GetLostReasonList()
    {
        return Util.GetPicklistValues(opportunity, 'factors__c');
    }
    
    public List <SelectOption> GetWonReasonList()
    {
        return Util.GetPicklistValues(opportunity, 'factors__c');
    }
    
    public List <SelectOption> GetCompetitorList()
    {
        return Util.GetPicklistValues(opportunity, 'competitors__c');
    }
    
    
    public List <SelectOption> GetContractTermList()
    {
        return Util.GetPicklistValues(opportunity, 'ContractTerm__c');
    }
    
    
    public PageReference upgrade()
    {
       
       List<opportunity>oList = new List<opportunity>();
       oList = [select id,name, Instance__c,Instance__r.id,Instance__r.Expiry_Date__c from opportunity where id =:opportunity.id limit 1];
       PageReference pg = new PageReference('/apex/productupdater?id='+olist[0].Instance__r.id+'&rec='+opportunity.id);
       pg.setRedirect(true);
       return pg; 

       
    }
    
}