DirOutput/objects/Instance__c.object
<CustomObject>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Instance_ID__c</fullName>
        <label>Instance ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Instance</label>
    <nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DirOutput/objects/KayakoAuditorKey__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>KayakoAuditorKey</label>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Instance_ID__c</fullName>
        <formula>Instance__r.Instance_ID__c</formula>
        <label>Instance ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Instance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Instance</label>
        <referenceTo>Instance__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KA_Product__c</fullName>
        <label>Product</label>
        <picklist>
            <picklistValues>
                <fullName>Fusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Growth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scale</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Instance_ID__c</fullName>
        <formula>Instance__r.Instance_ID__c</formula>
        <label>Instance ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Instance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Instance</label>
        <referenceTo>Instance__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <label>Plan</label>
        <picklist>
            <controllingField>Product__c</controllingField>
            <picklistValues>
                <fullName>Fusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Growth</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scale</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>Kayako 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Kayako 4 OnDemand)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Kayako 3 -&gt; 4 OnDemand)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Kayako 4 (July 2014))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (July 2016)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Download Perpetual Upgrade (July 2016))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Nov 2016)</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Download Perpetual Upgrade (Nov 2016))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 4 (Download Perpetual to Subscription (Dec 2016))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 4 Renewals (Nov 2010)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 4 Renewals (April 2013)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 4 OnDemand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 4 (July 2014)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 3 -&gt; 4 Renewals (Nov 2010)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 3 -&gt; 4 OnDemand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Kayako 4 (Download Perpetual to Subscription (Dec 2016)))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (June 2017)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Download Perpetual Upgrade (June 2017))</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DirOutput/classes/TestInstanceSyncController.cls
@isTest
public class TestInstanceSyncController{

public static testMethod void positiveScenario2(){
    
        KayakoAuditorKey__c km = new KayakoAuditorKey__c();
        km.name = 'tester';
        km.key__c = 'testing123';
        insert km;
        
        Instance__c i = new Instance__c();
        i.name = 'test.kayako.com';
        i.uuid__c = 'y3x-1111-33-444';
        i.instance_id__c = 2223;
        i.expiry_date__c = DateTime.now();
        insert i;
        
        Lead l = new Lead();
        l.company = 'test';
        l.email = 'test@test.com';
        l.lastname = 'test';
        l.ka_product__c = 'test';
        l.instance__c = i.id;
        insert l;
        
        test.startTest();
        /*ApexPages.StandardController sc = new ApexPages.StandardController(l);
        LeadButtonRenderer obj = new LeadButtonRenderer(sc);
        try{
        obj.GetCanAcceptOpenLead();
        obj.GetCanUpgrade();
        obj.GetCanMarkLeadContacted();
        obj.reject();
        obj.GetCanReopenLead();
        //obj.SeniorRoles();
        obj.GetCanConvertToContact();
        obj.convertToContact();
        }
        catch(exception e){}*/
        test.stopTest();
        
        }

    public static testMethod void positiveScenario(){
    
        KayakoAuditorKey__c km = new KayakoAuditorKey__c();
        km.name = 'tester';
        km.key__c = 'testing123';
        insert km;
        
        Instance__c i = new Instance__c();
        i.name = 'test.kayako.com';
        i.uuid__c = 'y3x-1111-33-444';
        i.instance_id__c = 2223;
        i.expiry_date__c = DateTime.now();
        insert i;
        
        Lead l = new Lead();
        l.company = 'test';
        l.email = 'test@test.com';
        l.lastname = 'test';
        l.ka_product__c = 'test';
        l.instance__c = i.id;
        insert l;
        
        
        Instance__c i2 = new Instance__c();
        i2.name = 'test.kayako.com';
        i2.uuid__c = 'y3x-1111-33-444';
        i2.instance_id__c = 2223;
        i2.expiry_date__c = DateTime.now();
        insert i2;
        
        Opportunity o = new Opportunity();
        o.name = 'test';
        o.product__c = 'test';
        o.plan__c ='test';
        o.instance__c = i2.id;
        o.stageName = 'Closed Won';
        o.CloseDate = Date.today();
        insert o;
        
        
        Test.setCurrentPageReference(new PageReference('Page.InstanceSync')); 
        System.currentPageReference().getParameters().put('id', i.id);
        ApexPages.StandardController sc = new ApexPages.StandardController(i);
        InstanceSyncController isc = new InstanceSyncController(sc);
        
        
        Test.setCurrentPageReference(new PageReference('Page.InstanceSync')); 
        System.currentPageReference().getParameters().put('id', i2.id);
        ApexPages.StandardController sc2 = new ApexPages.StandardController(i2);
        InstanceSyncController isc2 = new InstanceSyncController(sc2);
        
        
        
        Test.setCurrentPageReference(new PageReference('Page.InstanceHandler')); 
        System.currentPageReference().getParameters().put('id', i2.id);
        System.currentPageReference().getParameters().put('type', 'enable');
        InstanceHandlerController ihc0 = new  InstanceHandlerController();
        
        
        Test.setCurrentPageReference(new PageReference('Page.InstanceHandler')); 
        System.currentPageReference().getParameters().put('id', i2.id);
        System.currentPageReference().getParameters().put('type', 'disable');
        InstanceHandlerController ihc = new  InstanceHandlerController();
        ihc.goback();
        
        
        isc2.goBack();
        
    }
    
    public static testMethod void positiveScenarioInstanceSyncController2(){
    
        KayakoAuditorKey__c km = new KayakoAuditorKey__c();
        km.name = 'tester';
        km.key__c = 'testing123';
        insert km;
        
        Instance__c i = new Instance__c();
        i.name = 'test.kayako.com';
        i.uuid__c = 'y3x-1111-33-444';
        i.instance_id__c = 2223;
        i.expiry_date__c = DateTime.now();
        insert i;
        
        Lead l = new Lead();
        l.company = 'test';
        l.email = 'test@test.com';
        l.lastname = 'test';
        l.ka_product__c = 'test';
        l.instance__c = i.id;
        insert l;
        
        
        Instance__c i2 = new Instance__c();
        i2.name = 'test.kayako.com';
        i2.uuid__c = 'y3x-1111-33-444';
        i2.instance_id__c = 2223;
        i2.expiry_date__c = DateTime.now();
        insert i2;
        
        Opportunity o = new Opportunity();
        o.name = 'test';
        o.product__c = 'test';
        o.plan__c ='test';
        o.instance__c = i2.id;
        o.stageName = 'Closed Won';
        o.CloseDate = Date.today();
        insert o;
        
        
        Test.setCurrentPageReference(new PageReference('Page.InstanceSync')); 
        System.currentPageReference().getParameters().put('id', i.id);
        ApexPages.StandardController sc = new ApexPages.StandardController(i);
        InstanceSyncController2 isc = new InstanceSyncController2(sc);
        
        
        Test.setCurrentPageReference(new PageReference('Page.InstanceSync')); 
        System.currentPageReference().getParameters().put('id', i2.id);
        ApexPages.StandardController sc2 = new ApexPages.StandardController(i2);
        InstanceSyncController2 isc2 = new InstanceSyncController2(sc2);
        
        
        
        Test.setCurrentPageReference(new PageReference('Page.InstanceHandler')); 
        System.currentPageReference().getParameters().put('id', i2.id);
        System.currentPageReference().getParameters().put('type', 'enable');
        ApexPages.StandardController sc3 = new ApexPages.StandardController(i2);
        InstanceSyncController2 ihc0 = new  InstanceSyncController2(sc3);
        
        
        Test.setCurrentPageReference(new PageReference('Page.InstanceHandler')); 
        System.currentPageReference().getParameters().put('id', i2.id);
        System.currentPageReference().getParameters().put('type', 'disable');
        ApexPages.StandardController sc4 = new ApexPages.StandardController(i2);
        InstanceSyncController2 ihc = new  InstanceSyncController2(sc4);
        ihc.goback();
        
        
        isc2.goBack();
        
    }

}