DirOutput/objects/Instance__c.object
<CustomObject>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>DateTime</type>
    </fields>
    <label>Instance</label>
    <nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Instance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Instance</label>
        <referenceTo>Instance__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Trial_Expiry__c</fullName>
        <description>Trial expiry date</description>
        <inlineHelpText>Instance Trial expiry date</inlineHelpText>
        <label>Old Trial Expiry Date</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

DirOutput/classes/InstanceHandler.cls
Public class InstanceHandler {
    public static void updateTrialExpirydate(Map<Id, Instance__c> oldInstance, Map<Id, Instance__c> newInstance){
     
        Set<Id> instanceIds = new Set<Id>();
        
        for (Instance__c objInstance: newInstance.values()) {
            if(objInstance.Expiry_Date__c != oldInstance.get(objInstance.Id).Expiry_Date__c ) {
                instanceIds.add(objInstance.Id);
            }
        }
        
        if(!instanceIds.isEmpty()) {
            Map<Id, Lead> mapLeads = new Map<Id, Lead>();
            for (Lead leadObj: [Select Trial_Expiry__c, id, Instance__c from LEAD where Instance__c IN: instanceIds ]) {
                //if(objInstance.Expiry_Date__c != oldInstance.get(objInstance.Id).Expiry_Date__c ) {
                    mapLeads.put(leadObj.Id, new Lead(Id=leadObj.Id,Trial_Expiry__c = oldInstance.get(leadObj.Instance__c ).Expiry_Date__c));
                //}
            }
            
            if(!mapLeads.isEmpty()) {
                update mapLeads.values();
            }
        }
     
    }
    
}