DirOutput/objects/Instance__c.object
<CustomObject>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>DateTime</type>
    </fields>
    <label>Instance</label>
    <nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Instance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Instance</label>
        <referenceTo>Instance__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>MQL</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SRL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SQL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SDL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

DirOutput/classes/TestBatchUpdateStatusOnLeads.cls
/**
  * ───────────────────────────────────────────────────────────────────────────────────────────────┐
  * Type - Apex Test Class
  * ────────────────────────────────────────────────────────────────────────────────────────────────
  * @Object      None  
  * @Description This class will be used to test the batch class created
  * @OrigialCls  BatchUpdateStatusOnLeads
  * @Author      Manoj Sankaran
  * ───────────────────────────────────────────────────────────────────────────────────────────────┘
  * Modification Log
  * 09-21-2018 - Created by Manoj Sankaran
  * 
  */

@isTest(SeeAllData = false)
private class TestBatchUpdateStatusOnLeads {
  static testmethod void test_RunBatchUpdateStatusOnLeads() {
        
        User u = [Select Id, Name from user where Name = 'Backend Kayako' limit 1];
    
        System.runAs(u) {
              
            
            Instance__c ins = new Instance__c();
            ins.Name = 'Test Instance';
            ins.Expiry_Date__c = system.today().addDays(-30);
            insert ins;
            
            Lead objLead = new Lead(Company = 'JohnMiller', LastName = 'Mike', Status = 'Open', Stage__c = 'MQL',leadSource = 'Web',Instance__c = ins.id);
            insert objLead;
             
            Test.startTest();
                List<AsyncApexJob> listJob = [ Select id ,Status, ApexClass.Name from AsyncApexJob where Status='Running'];
                if(listJob == null || listJob.size() ==0 ) {
                    BatchUpdateStatusOnLeads bla= new BatchUpdateStatusOnLeads();
                    Database.executeBatch(bla);
                }
            Test.stopTest();
        }
    }
}