DirOutput/objects/Instance__c.object
<CustomObject>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Instance</label>
    <nameField>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ClosedBy__c</fullName>
        <label>ClosedBy</label>
        <picklist>
            <picklistValues>
                <fullName>Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Factors__c</fullName>
        <label>Factors</label>
        <picklist>
            <picklistValues>
                <fullName>Regional Issues/Data Residency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Feature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self Serve</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unresponsive/Timeline</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Instance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Instance</label>
        <referenceTo>Instance__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>Kayako 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Kayako 4 OnDemand)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Kayako 3 -&gt; 4 OnDemand)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Kayako 4 (July 2014))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (July 2016)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Download Perpetual Upgrade (July 2016))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Nov 2016)</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Download Perpetual Upgrade (Nov 2016))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 4 (Download Perpetual to Subscription (Dec 2016))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 4 Renewals (Nov 2010)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 4 Renewals (April 2013)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 4 OnDemand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 4 (July 2014)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 3 -&gt; 4 Renewals (Nov 2010)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako 3 -&gt; 4 OnDemand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Kayako 4 (Download Perpetual to Subscription (Dec 2016)))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (June 2017)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kayako (Download Perpetual Upgrade (June 2017))</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

DirOutput/classes/OpportunityButtonRendererTest.cls
@isTest
public class OpportunityButtonRendererTest 
{
    private static SObject opportunity;

    private static void createMock()
    {
        Test.setMock(HttpCalloutMock.class, new WebhookTest());
        
        opportunity = ObjectMocker.mock('Opportunity');
        opportunity.put('OwnerId', UserInfo.GetUserId());
        insert opportunity;
        ApexPages.currentPage().getParameters().put('id', opportunity.Id);
    }

    private static OpportunityButtonRenderer createRenderer()
    {
        ApexPages.StandardController controller = new ApexPages.StandardController(opportunity);
        return new OpportunityButtonRenderer(controller);
    }

    private static OpportunityButtonRenderer createHandler()
    {
        createMock();
        return createRenderer();
    }

    public static TestMethod void testConstructor()
    {
        createHandler();
    }

    public static TestMethod void testCanDemoOpportunity()
    {
        createMock();
        opportunity.put('StageName', OpportunityStage.VALUE_PROPOSITION);
        update opportunity;
        OpportunityButtonRenderer handler = createRenderer();

        System.assert(handler.GetCanDemoOpportunity());
    }


    public static TestMethod void testCanProjectPosponedOpportunity()
    {
        createMock();
        opportunity.put('StageName', OpportunityStage.VALUE_PROPOSITION);
        update opportunity;
        OpportunityButtonRenderer handler = createRenderer();

        System.assert(handler.GetCanProjectPostponedOpportunity());
    }

    public static TestMethod void testCanUpdatePriceOpportunity()
    {
        createMock();
        opportunity.put('StageName', OpportunityStage.VALUE_PROPOSITION);
        update opportunity;
        OpportunityButtonRenderer handler = createRenderer();

        System.assert(handler.GetCanUpdatePrice());
    }

    public static TestMethod void testGetCanMarkAsAcceptOpportunity(){
        createMock();
        opportunity.put('StageName', OpportunityStage.CREATED);
        update opportunity;
        OpportunityButtonRenderer handler = createRenderer();

        
    }

    public static TestMethod void testGetCanMarkAsRejectOpportunity(){
        createMock();
        opportunity.put('StageName', OpportunityStage.CREATED);
        update opportunity;
        OpportunityButtonRenderer handler = createRenderer();

        
    }

    public static testMethod void testCanUpgrade(){
        Instance__c i = new Instance__c();
        i.name = 'test.kayako.com';
        i.state__c = 'trial';
        i.expiry_date__c = date.today()-1;
        insert i;
        
        
        createMock();
        opportunity.put('Product__c','Kayako(Nov 2016)');
        opportunity.put('Instance__c',i.id);
        update opportunity;
        OpportunityButtonRenderer handler = createRenderer();
        
        
        System.assertEquals(false, handler.GetCanUpgrade());
    }


    public static TestMethod void testCanProvideProposalAndQuoteInValueProposition()
    {
        createMock();
        opportunity.put('StageName', OpportunityStage.VALUE_PROPOSITION);
        update opportunity;
        OpportunityButtonRenderer handler = createRenderer();

        System.assert(handler.GetCanProvideProposalAndQuote());
    }

    public static TestMethod void testCanProvideProposalAndQuoteInDemo()
    {
        createMock();
        opportunity.put('StageName', OpportunityStage.DEMO);
        update opportunity;
        OpportunityButtonRenderer handler = createRenderer();

        System.assert(handler.GetCanProvideProposalAndQuote());
    }

    public static TestMethod void testCannotMarkAsLostIfLost()
    {
        createMock();
        opportunity.put('StageName', 'Closed Lost: Dead');
        update opportunity;
        OpportunityButtonRenderer handler = createRenderer();

        
    }

    public static TestMethod void testCannotMarkAsLostIfWon()
    {
        createMock();
        opportunity.put('StageName', OpportunityStage.WON);
        update opportunity;
        OpportunityButtonRenderer handler = createRenderer();

        System.assert( ! handler.GetCanMarkAsLost());
    }

    public static TestMethod void testCanMarkAsWonInReviewAndNegotiation()
    {
        createMock();
        opportunity.put('StageName', OpportunityStage.REVIEW_AND_NEGOTIATION);
        update opportunity;
        OpportunityButtonRenderer handler = createRenderer();

        System.assertEquals(UserDataAccess.GetCurrentUser().Profile.Name == 'System Administrator', handler.GetCanMarkAsWon());
    }

    public static TestMethod void testCanMarkAsWonInProposalAndQuote()
    {
        createMock();
        opportunity.put('StageName', OpportunityStage.PROPOSAL_AND_QUOTE);
        update opportunity;
        OpportunityButtonRenderer handler = createRenderer();
        
        System.assertEquals(UserDataAccess.GetCurrentUser().Profile.Name == 'System Administrator', handler.GetCanMarkAsWon());
    }

    public static TestMethod void testCanReviewAndNegotiate()
    {
        createMock();
        opportunity.put('StageName', OpportunityStage.PROPOSAL_AND_QUOTE);
        update opportunity;
        OpportunityButtonRenderer handler = createRenderer();

        System.assert(handler.GetCanReviewAndNegotiate());
    }

    public static TestMethod void testCanProvideNewQuote()
    {
        createMock();
        opportunity.put('StageName', OpportunityStage.PROPOSAL_AND_QUOTE);
        update opportunity;
        OpportunityButtonRenderer handler = createRenderer();

        System.assert(handler.GetCanProvideNewQuote());
    }
    
    public static TestMethod void testCanUpdateInstance()
    {
        createMock();
        opportunity.put('StageName', OpportunityStage.PROPOSAL_AND_QUOTE);
        update opportunity;
        OpportunityButtonRenderer handler = createRenderer();

        System.assert(handler.GetCanUpdateInstanceDetails());
    }
    
    public static TestMethod void testCannotUpdateInstanceIfWon()
    {
        createMock();
        opportunity.put('StageName', OpportunityStage.WON);
        update opportunity;
        OpportunityButtonRenderer handler = createRenderer();

        System.assert( ! handler.GetCanUpdateInstanceDetails());
    }
    
    public static TestMethod void testCannotUpdateInstanceIfLost()
    {
        createMock();
        opportunity.put('StageName', 'Closed Lost: Dead');
        update opportunity;
        OpportunityButtonRenderer handler = createRenderer();

        
    }
    
    public static TestMethod void TestDemoOpportunity()
    {
        OpportunityButtonRenderer handler = createHandler();
        PageReference response = handler.DemoOpportunity();
        Opportunity subject = [SELECT Id, StageName FROM Opportunity WHERE Id = :opportunity.Id LIMIT 1];
        System.assert(subject.StageName == OpportunityStage.DEMO);
    }

    public static TestMethod void TestProjectPostponedOpportunity()
    {
        OpportunityButtonRenderer handler = createHandler();
        PageReference response = handler.ProjectPostponedOpportunity();
        Opportunity subject = [SELECT Id, StageName FROM Opportunity WHERE Id = :opportunity.Id LIMIT 1];
        System.assert(subject.StageName == OpportunityStage.PROJECT_POSTPONED);
    }

    public static TestMethod void TestMarkAsAcceptOpportunity()
    {
        OpportunityButtonRenderer handler = createHandler();
        PageReference response = handler.markAsAccept();
        Opportunity subject = [SELECT Id, StageName FROM Opportunity WHERE Id = :opportunity.Id LIMIT 1];
        System.assert(subject.StageName == OpportunityStage.VALUE_PROPOSITION);
    }

    public static TestMethod void TestMarkAsRejectOpportunity()
    {
        OpportunityButtonRenderer handler = createHandler();
        PageReference response = handler.markAsReject();
        Opportunity subject = [SELECT Id, StageName FROM Opportunity WHERE Id = :opportunity.Id LIMIT 1];
        System.assert(subject.StageName == OpportunityStage.REJECTED);
    }

    public static TestMethod void testProposalAndQuoteGiven()
    {
        OpportunityButtonRenderer handler = createHandler();
        PageReference response = handler.ProvideProposalAndQuote();
        Opportunity subject = [SELECT Id, StageName FROM Opportunity WHERE Id = :opportunity.Id LIMIT 1];
        System.assert(subject.StageName == OpportunityStage.PROPOSAL_AND_QUOTE);
    }

   

    public static TestMethod void testOpportunityIsWon()
    {
        OpportunityButtonRenderer handler = createHandler();
        PageReference response = handler.MarkAsWon();
        Opportunity subject = [SELECT Id, StageName, ClosedBy__c FROM Opportunity WHERE Id = :opportunity.Id LIMIT 1];

        System.assertEquals('Agent', subject.ClosedBy__C);
        System.assertEquals(OpportunityStage.WON, subject.StageName);
    }

    public static TestMethod void testUpdateWonReason()
    {
        OpportunityButtonRenderer handler = createHandler();
        PageReference response = handler.UpdateWonReason();
        Opportunity subject = [SELECT Id, factors__c,StageName, ClosedBy__c FROM Opportunity WHERE Id = :opportunity.Id LIMIT 1];

        System.assertEquals(null, subject.factors__c);
       // System.assertEquals(OpportunityStage.WON, subject.StageName);
    }

    public static TestMethod void testOpportunityIsLost()
    {
        OpportunityButtonRenderer handler = createHandler();
        handler.lostStage = 'Closed Lost: Dead';
        handler.lostReason ='test';
        PageReference response = handler.MarkAsLost();

        Opportunity subject = [SELECT Id, Factors__c,StageName, ClosedBy__c FROM Opportunity WHERE Id = :opportunity.Id LIMIT 1];

        System.assertEquals('Agent', subject.ClosedBy__C);
        System.assertEquals('test', subject.Factors__c);
        System.assertEquals('Closed Lost: Dead', subject.StageName);
    }

    public static TestMethod void testReviewAndNegotiate()
    {
        OpportunityButtonRenderer handler = createHandler();
        PageReference response = handler.ReviewAndNegotiate();
        Opportunity subject = [SELECT Id, StageName FROM Opportunity WHERE Id = :opportunity.Id LIMIT 1];
        System.assert(subject.StageName == OpportunityStage.REVIEW_AND_NEGOTIATION);
    }


}