DirOutput/objects/KayakoAuditorKey__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>KayakoAuditorKey</label>
</CustomObject>

src/objects/KayakoMetricsKey__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Kayako Metrics Key is used to communicate with backend to get the Metrics related to an Instance.</description>
    <fields>
        <fullName>Key__c</fullName>
        <description>This is secret key which is used to communicate with backend in order to get the metrics.</description>
        <label>Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>KayakoMetricsKey</label>
</CustomObject>

DirOutput/classes/TestScheduleBatchInstanceExpiry.cls
/*
    This class schedules the Batch Instance Expiry Class, which in turn runs the batch over the instances.
*/

@isTest
public class TestScheduleBatchInstanceExpiry {
    
    static  testMethod void TestSchedule(){
       
       KayakoMetricsKey__c kmk = new KayakoMetricsKey__c();
       kmk.name = 'test';
       kmk.key__c = 'testing';
       insert kmk;
       
       KayakoAuditorKey__c km = new KayakoAuditorKey__c();
       km.name = 'tester';
       km.key__c = 'testing123';
       insert km;
       
        String chron1 = '0 2 * * * ? *';      
        System.schedule('ScheduleBatchInstanceExpiryUpdater', chron1, new ScheduleBatchInstanceExpiryUpdater());
    
    }



}